import os

from dotenv import load_dotenv

# flake8: noqa=E501

load_dotenv(override=True)

NIEBIESKI_ZAPYTANIE_1_LOGIN = os.environ.get("NIEBIESKI_ZAPYTANIE_1_LOGIN")
NIEBIESKI_ZAPYTANIE_1_PASSWORD = os.environ.get("NIEBIESKI_ZAPYTANIE_1_PASSWORD")

NIEBIESKI_ZAPYTANIE_2_LOGIN = os.environ.get("NIEBIESKI_ZAPYTANIE_2_LOGIN")
NIEBIESKI_ZAPYTANIE_2_PASSWORD = os.environ.get("NIEBIESKI_ZAPYTANIE_2_PASSWORD")

NIEBIESKI_ZAPYTANIE_3_LOGIN = os.environ.get("NIEBIESKI_ZAPYTANIE_3_LOGIN")
NIEBIESKI_ZAPYTANIE_3_PASSWORD = os.environ.get("NIEBIESKI_ZAPYTANIE_3_PASSWORD")

NIEBIESKI_ZAPYTANIE_4_LOGIN = os.environ.get("NIEBIESKI_ZAPYTANIE_4_LOGIN")
NIEBIESKI_ZAPYTANIE_4_PASSWORD = os.environ.get("NIEBIESKI_ZAPYTANIE_4_PASSWORD")
