# flake8: noqa
from .base_admin import *
from .crm_todo_modeladmin import CrmTodoModelAdmin
from .discountcode_modeladmin import DiscountCodeModelAdmin
from .lecturer_modeladmin import LecturerModelAdmin
from .webinar_category_modeladmin import WebinarCategoryModelAdmin
from .webinar_certificate_modeladmin import WebinarCertificateModelAdmin
from .webinar_metadata_modeladmin import WebinarMetadataModelAdmin
from .webinar_modeladmin import WebinarModelAdmin
