class LeadSource:
    NOT_SPECIFIED = "NOT_SPECIFIED"
    WEBINAR_PARTICIPANT = "WEBINAR_PARTICIPANT"
    WEBINAR_CONTACT = "WEBINAR_CONTACT"
    NEWSLETTER_FOOTER = "NEWSLETTER_FOOTER"
    CONFERENCE_FREE = "CONFERENCE_FREE"
    CONFERENCE_PAID = "CONFERENCE_PAID"
    EMAIL_MESSAGE_SIGNUP = "EMAIL_MESSAGE_SIGNUP"
    ARCHIVED_WEBINAR = "ARCHIVED_WEBINAR"
