class WebinarApplicationType:
    JSFP = "JSFP"
    COMPANY = "COMPANY"
    PRIVATE_PERSON = "PRIVATE_PERSON"


class WebinarApplicationStep:
    APPLICATION_TYPE = "APPLICATION_TYPE"
    PERSON_DETAILS = "PERSON_DETAILS"
    BUYER = "BUYER"
    RECEIVER = "RECEIVER"
    INVOICE = "INVOICE"
    SUBMITTER = "SUBMITTER"
    PARTICIPANTS = "PARTICIPANTS"
    ADDITIONAL_INFO = "ADD_INFO"
    SUMMARY = "SUMMARY"


class WebinarStatus:
    INIT = "INIT"
    CONFIRMED = "CONFIRMED"
    CANCELED = "CANCELED"
    DONE = "DONE"
