"""Aggressor phrases"""

AGGRESSOR_PHRASES_ICONTAINS = [
    "kurwa",
    "kurwo",
    "kurwy",
    "kurwi",
    "pierdol",
    "pierdal",
    "jeban",
    "odjeb",
    "chuj",
    "gówn",
    "skąd macie",
    "skąd mają państwo",
    "skąd państwo mają",
    "skąd macie moje",
    " zaprzestać wysyłania",
    " zaprzestanie wysyłania",
    " zaprzestać wysyłania",
    " zaprzestać przesyłania",
    " przestańcie wysyłać",
    " spamerzy",
    " spamerskie",
    "wysyłać spam",
    "wysyłają spam",
    " jakim prawem ",
]
