"""Aggressor phrases"""

AGGRESSOR_PHRASES_ICONTAINS = [
    "dziwko",
    "dziwka",
    "dziwki",
    "kurwa",
    "kurwo",
    "kurwy",
    "kurwi",
    "pierdol",
    "pierdal",
    "jeban",
    "odjeb",
    " chuj",
    "chuju",
    "chujowy",
    "chujowe",
    "chujowi",
    "gówn",
    "skąd macie",
    "skąd mają państwo",
    "skąd państwo mają",
    "skąd macie moje",
    " zaprzestać wysyłania",
    " zaprzestanie wysyłania",
    " zaprzestać przesyłania",
    " przestańcie wysyłać",
    " spamerzy",
    " spamerskie",
    " spamować",
    "wysyłać spam",
    "wysyłają spam",
    " jakim prawem ",
]
