# flake8: noqa
from .application_discount_panel import application_discount_panel
from .crm_lecturer_price_card import crm_lecturer_price_card
from .crm_todo_htmx import htmx_toggle_crm_todo
from .crm_webinar_assets_htmx import htmx_delete_webinar_asset
