from django.urls import path

from core.views.crm import (
    crm_archived_webinars,
    crm_eventlogs,
    crm_todos_done_list,
    crm_todos_list,
    crm_upcoming_webinars,
    crm_webinar_assets,
    crm_webinar_confirm,
    crm_webinar_detail_dashboard,
    crm_webinar_done,
    crm_webinar_eventlogs,
    crm_webinar_participants,
)

urlpatterns = [
    path(
        "webinar/<int:pk>/",
        crm_webinar_detail_dashboard,
        name="crm_webinar_detail_dashboard",
    ),
    path(
        "webinar/<int:pk>/logi/",
        crm_webinar_eventlogs,
        name="crm_webinar_eventlogs",
    ),
    path(
        "webinar/<int:pk>/uczestnicy/",
        crm_webinar_participants,
        name="crm_webinar_participants",
    ),
    path(
        "webinar/<int:pk>/materialy-szkoleniowe/",
        crm_webinar_assets,
        name="crm_webinar_assets",
    ),
    path(
        "webinar/<int:pk>/potwierdz-termin/",
        crm_webinar_confirm,
        name="crm_webinar_confirm",
    ),
    path(
        "webinar/<int:pk>/zakoncz-szkolenie/",
        crm_webinar_done,
        name="crm_webinar_done",
    ),
    path(
        "archiwum/",
        crm_archived_webinars,
        name="crm_archived_webinars",
    ),
    path(
        "zadania/wykonane/",
        crm_todos_done_list,
        name="crm_todos_done_list",
    ),
    path(
        "zadania/",
        crm_todos_list,
        name="crm_todos_list",
    ),
    path(
        "logi/",
        crm_eventlogs,
        name="crm_eventlogs",
    ),
    path(
        "",
        crm_upcoming_webinars,
        name="crm_upcoming_webinars",
    ),
]
