# flake8: noqa
from .crm_are_you_sure_form import CrmAreYouSureForm
from .crm_lecturer_add_opinions_form import CrmLecturerAddOpinionsForm
from .crm_lecturer_price_card_form import CrmLecturerPriceCardForm
from .crm_move_action_form import CrmMoveActionForm
