# flake8: noqa
from .lecturer_add_opinions_page import lecturer_add_opinions_page
from .lecturer_list_page import lecturer_list_page
from .lecturer_participants_emails_page import lecturer_participants_emails_page
from .lecturer_stats_page import lecturer_stats_page
