from .webinar_lecturer_biography_page import webinar_lecturer_biography_page
from .webinar_opinions_page import webinar_opinions_page
from .webinar_price_and_invoice_page import webinar_price_and_invoice_page
from .webinar_program_page import webinar_program_page
