# Generated by Django 4.2.2 on 2023-07-10 16:56

import core.libs.validators.nip_validator
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.EmailField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visible_on_page",
                    models.BooleanField(
                        default=True,
                        help_text="Czy wykładowca ma być widoczny na stronie",
                        verbose_name="Widoczny na stronie",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=100, verbose_name="Imie i Nazwisko"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)",
                        max_length=120,
                        verbose_name="Skrót URL",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Obrazek powinien być dobrej jakościo wymiarach kwadratowych (np. 500px na 500px)",
                        upload_to="uploads/lecturers",
                        verbose_name="Avatar",
                    ),
                ),
                ("biography", models.TextField(blank=True, verbose_name="Biografia")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail kontaktowy do wykładowcy",
                        max_length=254,
                        verbose_name="Adres E-mail",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True,
                        help_text="Widoczna na stronie webinaru pod imieniem i nazwiskiem",
                        max_length=40,
                        verbose_name="Profesja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wykładowca",
                "verbose_name_plural": "Wykładowcy",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Webinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Pokaż `Pewny termin` przy szkoleniu na stronie",
                        verbose_name="Pewny termin",
                    ),
                ),
                (
                    "remaining_places",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, verbose_name="Pozostało miejsc"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INIT", "Termin wystawiony"),
                            ("CONFIRMED", "Termin potwierdzony"),
                            ("CANCELED", "Termin odwołany"),
                            ("DONE", "Termin zrealizowany"),
                        ],
                        default="INIT",
                        max_length=32,
                    ),
                ),
                (
                    "title_original",
                    models.TextField(
                        help_text="Tytuł szkolenia jaki został dostarczony przez wykładowce",
                        verbose_name="Pełny tytuł szkolenia",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Tytuł szkolenia zmodyfikowany, aby mieścił się w ogrniczonej ilości znaków",
                        max_length=220,
                        verbose_name="Tytuł szkolenia",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)",
                        max_length=230,
                        unique=True,
                        verbose_name="Skrót URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Dodatkowy opis webinaru",
                        max_length=200,
                        verbose_name="Dodatkowy opis",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Data i Godzina")),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("60", "1 godzina"),
                            ("90", "1,5 godziny"),
                            ("120", "2 godziny"),
                            ("150", "2,5 godziny"),
                            ("180", "3 godziny"),
                            ("210", "3,5 godziny"),
                            ("240", "4 godziny"),
                            ("270", "4,5 godziny"),
                            ("300", "5 godzin"),
                            ("330", "5,5 godziny"),
                            ("360", "6 godzin"),
                            ("390", "6,5 godziny"),
                            ("420", "7 godzin"),
                            ("450", "7,5 godziny"),
                            ("480", "8 godzin"),
                            ("510", "8,5 godziny"),
                            ("540", "9 godzin"),
                        ],
                        default="240",
                        max_length=16,
                        verbose_name="Czas trwania",
                    ),
                ),
                (
                    "price_netto",
                    models.PositiveSmallIntegerField(verbose_name="Cena NETTO"),
                ),
                (
                    "discount_netto",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Cena NETTO (Promocyjna)"
                    ),
                ),
                (
                    "discount_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Promocja do"
                    ),
                ),
                (
                    "program",
                    models.TextField(
                        default="[Program Szkolenia]", verbose_name="Program szkolenia"
                    ),
                ),
                (
                    "program_markdown",
                    models.TextField(
                        blank=True, verbose_name="Program szkolenia (markdown)"
                    ),
                ),
                (
                    "program_enchanted",
                    models.TextField(
                        blank=True, verbose_name="Program szkolenia (enchanted)"
                    ),
                ),
                (
                    "external_name",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Zewnętrzny dostawca - Nazwa",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, verbose_name="Zewnętrzny dostawca - URL"
                    ),
                ),
                (
                    "external_description",
                    models.TextField(
                        blank=True, verbose_name="Zewnętrzny dostawca - Opis"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webinar",
                "verbose_name_plural": "Webinary",
                "ordering": ["date"],
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebinarApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INIT", "Zgłoszenie rozpoczęte"),
                            ("SENT", "Zgłoszenie wysłane"),
                            ("RESIGNATION", "Rezygnacja ze zgłoszenia"),
                        ],
                        default="INIT",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Stworzono"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Identyfikator zgłoszenia",
                    ),
                ),
                (
                    "discount_applied",
                    models.BooleanField(
                        default=False, verbose_name="Promocja nałożona"
                    ),
                ),
                (
                    "price_netto",
                    models.PositiveSmallIntegerField(verbose_name="Cena NETTO"),
                ),
                (
                    "price_old",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Stara cena"
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Firma"),
                            ("JSFP", "JSFP"),
                            ("PRIVATE_PERSON", "Osoba prywatna"),
                        ],
                        default="COMPANY",
                        max_length=64,
                        verbose_name="Typ zgłoszenia",
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(blank=True, verbose_name="Uwagi"),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie",
                "verbose_name_plural": "Zgłoszenia",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebinarApplicationCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nip",
                    models.CharField(
                        max_length=32,
                        validators=[
                            core.libs.validators.nip_validator.validate_nip_modelfield
                        ],
                        verbose_name="NIP",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nazwa")),
                ("address", models.CharField(max_length=150, verbose_name="Adres")),
                (
                    "postal_code",
                    models.CharField(max_length=16, verbose_name="Kod pocztowy"),
                ),
                ("city", models.CharField(max_length=150, verbose_name="Miejscowość")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Telefon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebinarApplicationInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("INVOICE_DIGITAL", "Faktura elektroniczna"),
                            ("INVOICE_PAPER", "Faktura elektroniczna i papierowa"),
                        ],
                        default="INVOICE_DIGITAL",
                        max_length=64,
                        verbose_name="Typ faktury",
                    ),
                ),
                (
                    "invoice_email",
                    models.EmailField(
                        help_text="E-mail na który zostanie przesłana faktura",
                        max_length=254,
                        verbose_name="E-mail (Faktura)",
                    ),
                ),
                (
                    "invoice_additional_info",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        verbose_name="Dodatkowe informacje (Faktura)",
                    ),
                ),
                (
                    "vat_exemption",
                    models.CharField(
                        choices=[
                            ("VAT_EXEMPTION_0", "Brak zwolnienia z VAT"),
                            (
                                "VAT_EXEMPTION_13",
                                "art. 43. ust. 1 pkt 29 lit. c - Szkolenia zawodowe finansowane ze środków publicznych",
                            ),
                            (
                                "VAT_EXEMPTION_36",
                                "par. 3. ust. 1 pkt 14 - Szkolenia zawodowe dofinansowane co najmniej w 70% ze środków publicznych",
                            ),
                            (
                                "VAT_EXEMPTION_113",
                                "Faktura wystawiana bez podatku VAT na podstawie art. 113 ust. 1 i 9 ustawy o VAT",
                            ),
                        ],
                        default="VAT_EXEMPTION_0",
                        max_length=64,
                        verbose_name="Zwolnienie z VAT",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebinarApplicationPrivatePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                ("address", models.CharField(max_length=150, verbose_name="Adres")),
                (
                    "postal_code",
                    models.CharField(max_length=16, verbose_name="Kod pocztowy"),
                ),
                ("city", models.CharField(max_length=150, verbose_name="Miejscowość")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Numer telefonu"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebinarApplicationSubmitter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_participant",
                    models.BooleanField(
                        default=False, verbose_name="Jest też uczestnikiem"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Numer telefonu"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebinarParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numer telefonu"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                        verbose_name="Zgłoszenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uczestnik",
                "verbose_name_plural": "Uczestnicy",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebinarRecording",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Pokaż nagranie na stronie",
                        verbose_name="Widoczne na stronie",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DOWNLOADING", "W trakcie pobierania nagrania"),
                            ("DOWNLOADED", "Pobrano nagranie"),
                            ("FAILED", "Wystąpił błąd podczas pobierania"),
                        ],
                        default="DOWNLOADING",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "recording_id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID nagrania",
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(verbose_name="URL do pobrania nagrania"),
                ),
                (
                    "recording_duration_seconds",
                    models.PositiveIntegerField(
                        verbose_name="Czas trwania nagrania (sekundy)"
                    ),
                ),
                (
                    "recorder_started",
                    models.DateTimeField(verbose_name="Kiedy rozpoczęto nagrywanie"),
                ),
                (
                    "recording_file_size",
                    models.CharField(max_length=64, verbose_name="Rozmiar nagrania"),
                ),
                (
                    "recording_name",
                    models.CharField(max_length=500, verbose_name="Nazwa nagrania"),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nagranie",
                "verbose_name_plural": "Nagrania",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebinarRecordingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Token nagrania"
                    ),
                ),
                (
                    "deny_access",
                    models.BooleanField(
                        default=True,
                        help_text="Zaznacz aby odmówić dostępu do nagrania przez ten token",
                        verbose_name="Odmówiono dostępu",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Puste pole oznacza, że token nie wygasa nigdy",
                        null=True,
                        verbose_name="Token wygasa",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarparticipant",
                        verbose_name="Uczestnik",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarrecording",
                        verbose_name="Nagranie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nagranie (token)",
                "verbose_name_plural": "Nagrania (tokeny)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebinarParticipantMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phoned",
                    models.BooleanField(
                        default=False, verbose_name="Czy zadzwoniono przed szkoleniem?"
                    ),
                ),
                (
                    "is_mx_valid",
                    models.CharField(
                        choices=[
                            ("NOT_CHECKED", "Nie sprawdzono"),
                            ("INVALID", "MX ustawiony"),
                            ("VALID", "brak MX"),
                        ],
                        default="NOT_CHECKED",
                        max_length=32,
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarparticipant",
                        verbose_name="Uczestnik",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebinarMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clickmeeting_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ClickMeeting ID"
                    ),
                ),
                (
                    "auto_send_invoices",
                    models.BooleanField(
                        default=True,
                        help_text="Czy po zrealizowanym szkoleniu faktury mają być wysłane automatycznie do wszystkich",
                        verbose_name="Automatyczne wysyłanie faktur",
                    ),
                ),
                (
                    "lecturer_price_netto",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Cena NETTO wykładowcy"
                    ),
                ),
                (
                    "assets_token",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="Token dostępu do materiałów"
                    ),
                ),
                (
                    "webinar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webinar"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebinarCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Identyfikator certyfikatu",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                ("title", models.TextField(verbose_name="Tytuł szkolenia")),
                ("issue_date", models.DateField(verbose_name="Data wystawienia")),
                (
                    "hours",
                    models.CharField(
                        help_text="Przykład: `4 godziny`",
                        max_length=20,
                        verbose_name="Czas trwania",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarparticipant",
                        verbose_name="Uczestnik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certyfikat",
                "verbose_name_plural": "Certyfikaty",
            },
        ),
        migrations.CreateModel(
            name="WebinarCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True, verbose_name="Widoczna na stronie"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa kategorii"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)",
                        max_length=120,
                        unique=True,
                        verbose_name="Skrót URL",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Im niższa wartość tym wyższa pozycja kategorii przy wyświetlaniu",
                        verbose_name="Pozycja",
                    ),
                ),
                (
                    "is_homepage_category",
                    models.BooleanField(
                        default=False, verbose_name="Jest kategorią domową"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kategoria nadrzędna",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarcategory",
                        verbose_name="Rodzic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria",
                "verbose_name_plural": "Kategorie",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebinarAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Token materiału"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=300, verbose_name="Nazwa pliku"),
                ),
                (
                    "filesize",
                    models.CharField(max_length=80, verbose_name="Rozmiar pliku"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Typ MIME"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/webinar_assets", verbose_name="Plik"
                    ),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materiał szkoleniowy",
                "verbose_name_plural": "Materiały szkoleniowe",
                "ordering": ["-created_at"],
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebinarApplicationMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phoned", models.BooleanField(default=False)),
                ("invoice_id", models.CharField(blank=True, max_length=32)),
                ("invoice_number", models.CharField(blank=True, max_length=64)),
                ("invoice_url", models.CharField(blank=True, max_length=300)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="buyer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_buyer",
                to="core.webinarapplicationcompany",
                verbose_name="Nabywca",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_invoice",
                to="core.webinarapplicationinvoice",
                verbose_name="Faktura",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="private_person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_private_person",
                to="core.webinarapplicationprivateperson",
                verbose_name="Osoba prywatna",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="recipient",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_recipient",
                to="core.webinarapplicationcompany",
                verbose_name="Odbiorca",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="submitter",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_submitter",
                to="core.webinarapplicationsubmitter",
                verbose_name="Osoba zgłaszająca",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Użytkownik",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="webinar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.webinar",
                verbose_name="Webinar",
            ),
        ),
        migrations.AddField(
            model_name="webinar",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="core.webinarcategory", verbose_name="Kategorie"
            ),
        ),
        migrations.AddField(
            model_name="webinar",
            name="lecturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.lecturer",
                verbose_name="Wykładowca",
            ),
        ),
        migrations.CreateModel(
            name="LecturerOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visible_on_page",
                    models.BooleanField(
                        default=False, verbose_name="Widoczna na stronie"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=100, verbose_name="Imię i Nazwisko"),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Firma"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stanowisko"
                    ),
                ),
                ("opinion_text", models.TextField(verbose_name="Treść opinii")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1stars", "1 gwiazdka"),
                            ("2stars", "2 gwiazdki"),
                            ("3stars", "3 gwiazdki"),
                            ("4stars", "4 gwiazdki"),
                            ("5stars", "5 gwiazdek"),
                        ],
                        max_length=16,
                        verbose_name="Ocena",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.lecturer",
                        verbose_name="Wykładowca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opinia o wykładowcy",
                "verbose_name_plural": "Opinie o wykładowcy",
            },
        ),
        migrations.AddField(
            model_name="lecturer",
            name="categories",
            field=models.ManyToManyField(
                to="core.webinarcategory", verbose_name="Kategorie"
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Użytkownik",
            ),
        ),
        migrations.CreateModel(
            name="Eventlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title_html", models.TextField(verbose_name="Tytuł (HTML)")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="Treść (HTML)"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=32, verbose_name="Ikona"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=32, verbose_name="Kolor"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                        verbose_name="Zgłoszenie",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarparticipant",
                        verbose_name="Uczestnik",
                    ),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CrmTodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Wykonano zadanie"),
                ),
                ("title", models.CharField(max_length=350, verbose_name="Tytuł")),
                ("html", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=64, verbose_name="Ikona"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=64, verbose_name="Kolor"),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=200, verbose_name="URL"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                        verbose_name="Zgłoszenie",
                    ),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie",
                "verbose_name_plural": "Zadania",
            },
        ),
    ]
