# Generated by Django 4.2.2 on 2023-06-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarapplication",
            name="buyer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_buyer",
                to="core.webinarapplicationcompany",
                verbose_name="Nabywca",
            ),
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_invoice",
                to="core.webinarapplicationinvoice",
                verbose_name="Faktura",
            ),
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="receiver",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_receiver",
                to="core.webinarapplicationcompany",
                verbose_name="Odbiorca",
            ),
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="submitter",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_submitter",
                to="core.webinarapplicationsubmitter",
                verbose_name="Osoba zgłaszająca",
            ),
        ),
    ]
