# Generated by Django 4.2.2 on 2023-06-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa kategorii"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="Skrót URL"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Pozycja"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarcategory",
                        verbose_name="Rodzic",
                    ),
                ),
            ],
        ),
    ]
