# Generated by Django 4.2.2 on 2023-07-12 09:34

import core.libs.validators.nip_validator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nip",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            core.libs.validators.nip_validator.validate_nip_modelfield
                        ],
                        verbose_name="NIP",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Nazwa Firmy")),
            ],
            options={
                "verbose_name": "CRM Firma",
                "verbose_name_plural": "CRM Firmy",
            },
        ),
        migrations.CreateModel(
            name="CrmContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adres E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "CRM Reprezentant",
                "verbose_name_plural": "CRM Reprezentanci",
            },
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("INIT", "Zgłoszenie rozpoczęte"),
                    ("SENT", "Zgłoszenie wysłane"),
                    ("RESIGNATION", "Rezygnacja ze zgłoszenia"),
                    ("PAYED", "Faktura opłacona"),
                ],
                default="INIT",
                max_length=32,
            ),
        ),
    ]
