# Generated by Django 4.2.2 on 2023-06-18 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_webinarcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=100, verbose_name="Imie i Nazwisko"),
                ),
                ("slug", models.SlugField(max_length=120, verbose_name="Nazwa w URL")),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="", verbose_name="Avatar"),
                ),
                ("biography", models.TextField(blank=True, verbose_name="Biografia")),
                (
                    "categories",
                    models.ManyToManyField(
                        to="core.webinarcategory", verbose_name="Kategorie"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
            ],
        ),
    ]
