# Generated by Django 4.2.2 on 2023-06-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_webinarapplication_buyer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarApplicationPrivatePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                ("address", models.CharField(max_length=150, verbose_name="Adres")),
                (
                    "postal_code",
                    models.CharField(max_length=16, verbose_name="Kod pocztowy"),
                ),
                ("city", models.CharField(max_length=150, verbose_name="Miejscowość")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Numer telefonu"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="webinarapplicationcompany",
            name="city",
            field=models.CharField(max_length=150, verbose_name="Miejscowość"),
        ),
        migrations.AlterField(
            model_name="webinarapplicationinvoice",
            name="vat_exemption",
            field=models.CharField(
                choices=[
                    ("VAT_EXEMPTION_0", "Brak zwolnienia z VAT"),
                    (
                        "VAT_EXEMPTION_13",
                        "art. 43. ust. 1 pkt 29 lit. c - Szkolenia zawodowe finansowane ze środków publicznych",
                    ),
                    (
                        "VAT_EXEMPTION_36",
                        "par. 3. ust. 1 pkt 14 - Szkolenia zawodowe dofinansowane co najmniej w 70% ze środków publicznych",
                    ),
                ],
                default="VAT_EXEMPTION_0",
                max_length=64,
                verbose_name="Zwolnienie z VAT",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="private_person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_private_person",
                to="core.webinarapplicationprivateperson",
                verbose_name="Osoba prywatna",
            ),
        ),
    ]
