# Generated by Django 4.2.2 on 2023-07-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_crmcompany_crmcontact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplication",
            name="ref_code",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Kod referencyjny"
            ),
        ),
    ]
