# Generated by Django 4.2.2 on 2023-07-12 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_webinarapplication_ref_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webinarapplication",
            old_name="ref_code",
            new_name="refcode",
        ),
    ]
