# Generated by Django 4.2.2 on 2023-06-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_lecturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INIT", "Termin wystawiony"),
                            ("CONFIRMED", "Termin potwierdzony"),
                            ("CANCELED", "Termin odwołany"),
                            ("DONE", "Termin zrealizowany"),
                        ],
                        default="INIT",
                        max_length=32,
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        max_length=220, verbose_name="Pełny tytuł szkolenia"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=230, unique=True, verbose_name="Skrót URL"
                    ),
                ),
                (
                    "title_short",
                    models.TextField(max_length=100, verbose_name="Krótki tytuł"),
                ),
                (
                    "title_desc",
                    models.TextField(blank=True, verbose_name="Krótki opis"),
                ),
                ("date", models.DateTimeField(verbose_name="Data i Godzina")),
                (
                    "price_netto",
                    models.PositiveSmallIntegerField(verbose_name="Cena NETTO"),
                ),
                (
                    "discount_netto",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Cena NETTO (Promocyjna)"
                    ),
                ),
                (
                    "discount_until",
                    models.DateTimeField(blank=True, verbose_name="Promocja do"),
                ),
                ("program", models.TextField()),
                (
                    "external_name",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Zewnętrzny dostawca - Nazwa",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, verbose_name="Zewnętrzny dostawca - URL"
                    ),
                ),
                (
                    "external_description",
                    models.TextField(
                        blank=True, verbose_name="Zewnętrzny dostawca - Opis"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        to="core.webinarcategory", verbose_name="Kategorie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin webinaru",
                "verbose_name_plural": "Terminy webinarów",
            },
        ),
        migrations.CreateModel(
            name="WebinarMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clickmeeting_id", models.CharField(blank=True, max_length=100)),
                ("auto_send_invoices", models.BooleanField(default=False)),
                (
                    "webinar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.webinar"
                    ),
                ),
            ],
        ),
    ]
