# Generated by Django 4.2.2 on 2023-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_webinarapplicationprivateperson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="duration",
            field=models.CharField(
                choices=[
                    ("60", "1 godzina"),
                    ("90", "1,5 godziny"),
                    ("120", "2 godziny"),
                    ("150", "2,5 godziny"),
                    ("180", "3 godziny"),
                    ("210", "3,5 godziny"),
                    ("240", "4 godziny"),
                    ("270", "4,5 godziny"),
                    ("300", "5 godzin"),
                    ("330", "5,5 godziny"),
                    ("360", "6 godzin"),
                    ("390", "6,5 godziny"),
                    ("420", "7 godzin"),
                    ("450", "7,5 godziny"),
                    ("480", "8 godzin"),
                    ("510", "8,5 godziny"),
                    ("540", "9 godzin"),
                ],
                default="240",
                max_length=16,
                verbose_name="Czas trwania",
            ),
        ),
    ]
