# Generated by Django 4.2.2 on 2023-06-18 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_webinar_webinarmetadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecturer",
            options={"verbose_name": "Wykładowca", "verbose_name_plural": "Wykładowcy"},
        ),
    ]
