# Generated by Django 4.2.2 on 2023-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_webinar_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarcategory",
            name="is_homepage_category",
            field=models.BooleanField(
                default=False, verbose_name="Jest kategorią domową"
            ),
        ),
    ]
