# Generated by Django 4.2.2 on 2023-06-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_webinarcategory_is_homepage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplication",
            name="price_old",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Stara cena"
            ),
        ),
    ]
