# Generated by Django 4.2.2 on 2023-07-12 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_webinarapplication_discount_applied"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Identyfikator kodu promocyjnego",
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Kod promocyjny"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False,
                        help_text="Kod został zużyty.",
                        verbose_name="Zużyty",
                    ),
                ),
                (
                    "use_type",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "Jednorazowy"),
                            ("MANY_TIMES", "Wielorazowy"),
                        ],
                        max_length=32,
                        verbose_name="Typ użycia",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENT", "( % ) Procentowa"),
                            ("VALUE", "( zł ) Złotówkowa"),
                        ],
                        max_length=32,
                        verbose_name="Typ zniżki",
                    ),
                ),
                (
                    "expires",
                    models.DateTimeField(
                        blank=True,
                        help_text="Jeżeli nie ustawiono znaczy, że nie wygasa.",
                        null=True,
                        verbose_name="Zniżka wygasa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kod promocyjny",
                "verbose_name_plural": "Kody promocyjne",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DiscountApplicationApplied",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.SmallIntegerField(verbose_name="Wartość zniżki (zł)"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Krótka nazwa")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Krótki opis"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.webinarapplication",
                        verbose_name="Zgłoszenie",
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.discountcode",
                        verbose_name="Kod promocyjny",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zniżka (zgłoszenie)",
                "verbose_name_plural": "Zniżka (zgłoszenia)",
            },
        ),
    ]
