# Generated by Django 4.2.2 on 2023-06-18 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_lecturer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webinarcategory",
            options={"verbose_name": "Kategoria", "verbose_name_plural": "Kategorie"},
        ),
    ]
