# Generated by Django 4.2.2 on 2023-06-18 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_webinarcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarcategory",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Im niższa wartość tym wyższa pozycja kategorii przy wyświetlaniu",
                verbose_name="Pozycja",
            ),
        ),
        migrations.AlterField(
            model_name="webinarcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Kategoria nadrzędna",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.webinarcategory",
                verbose_name="Rodzic",
            ),
        ),
    ]
