# Generated by Django 4.2.2 on 2023-06-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_webinarapplication_price_old"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarapplicationinvoice",
            name="vat_exemption",
            field=models.CharField(
                choices=[
                    ("VAT_EXEMPTION_0", "Brak zwolnienia z VAT"),
                    (
                        "VAT_EXEMPTION_13",
                        "art. 43. ust. 1 pkt 29 lit. c - Szkolenia zawodowe finansowane ze środków publicznych",
                    ),
                    (
                        "VAT_EXEMPTION_36",
                        "par. 3. ust. 1 pkt 14 - Szkolenia zawodowe dofinansowane co najmniej w 70% ze środków publicznych",
                    ),
                    (
                        "VAT_EXEMPTION_113",
                        "Faktura wystawiana bez podatku VAT na podstawie art. 113 ust. 1 i 9 ustawy o VAT",
                    ),
                ],
                default="VAT_EXEMPTION_0",
                max_length=64,
                verbose_name="Zwolnienie z VAT",
            ),
        ),
    ]
