# Generated by Django 4.2.2 on 2023-06-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_webinarapplicationinvoice_vat_exemption"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webinarparticipant",
            options={"verbose_name": "Uczestnik", "verbose_name_plural": "Uczestnicy"},
        ),
        migrations.AddField(
            model_name="webinarapplicationmetadata",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="webinarapplicationmetadata",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="webinarapplicationmetadata",
            name="invoice_url",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="webinarmetadata",
            name="is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Oznacza termin jako `Termin potwierdzony` na stronie. To czysto kosmetyczna funkcja.",
                verbose_name="Termin potwierdzony",
            ),
        ),
    ]
