# Generated by Django 4.2.2 on 2023-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_webinarcategory_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarcategory",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)",
                max_length=120,
                unique=True,
                verbose_name="Skrót URL",
            ),
        ),
    ]
