# Generated by Django 4.2.2 on 2023-06-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_webinarparticipant_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmTodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Wykonano zadanie"),
                ),
                ("title", models.CharField(max_length=350, verbose_name="Tytuł")),
                ("html", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=64, verbose_name="Ikona"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=64, verbose_name="Kolor"),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=200, verbose_name="URL"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                        verbose_name="Zgłoszenie",
                    ),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie",
                "verbose_name_plural": "Zadania",
            },
        ),
    ]
