# Generated by Django 4.2.2 on 2023-06-19 10:46

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_webinarcategory_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webinar",
            options={"verbose_name": "Webinar", "verbose_name_plural": "Webinary"},
        ),
        migrations.RemoveField(
            model_name="webinar",
            name="title_desc",
        ),
        migrations.RemoveField(
            model_name="webinar",
            name="title_short",
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Obrazek powinien być dobrej jakości o wymiarach kwadratowych (np. 500px na 500px)",
                upload_to="uploads/lecturers",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="biography",
            field=django_quill.fields.QuillField(blank=True, verbose_name="Biografia"),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)",
                max_length=120,
                verbose_name="Skrót URL",
            ),
        ),
        migrations.AlterField(
            model_name="webinar",
            name="program",
            field=django_quill.fields.QuillField(verbose_name="Program szkolenia"),
        ),
    ]
