# Generated by Django 4.2.2 on 2023-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_discountcode_discount_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectureropinion",
            name="opinion_hash",
            field=models.CharField(blank=True, max_length=100, verbose_name="HASH"),
        ),
        migrations.AlterField(
            model_name="webinarrecordingtoken",
            name="deny_access",
            field=models.BooleanField(
                default=False,
                help_text="Zaznacz aby odmówić dostępu do nagrania przez ten token",
                verbose_name="Odmówiono dostępu",
            ),
        ),
    ]
