# Generated by Django 4.2.2 on 2023-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_webinar_options_remove_webinar_title_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="slug",
            field=models.SlugField(
                help_text="Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)",
                max_length=120,
                verbose_name="Skrót URL",
            ),
        ),
        migrations.AlterField(
            model_name="webinar",
            name="discount_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Promocja do"
            ),
        ),
    ]
