# Generated by Django 4.2.2 on 2023-06-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_crmtodo"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarParticipantMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phoned", models.BooleanField(default=False)),
                (
                    "is_mx_valid",
                    models.CharField(
                        choices=[
                            ("NOT_CHECKED", "Nie sprawdzono"),
                            ("INVALID", "MX ustawiony"),
                            ("VALID", "brak MX"),
                        ],
                        default="NOT_CHECKED",
                        max_length=32,
                    ),
                ),
                ("confirmation_email_opened", models.BooleanField(default=False)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarparticipant",
                        verbose_name="Uczestnik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uczestnik",
                "verbose_name_plural": "Uczestnicy",
            },
        ),
    ]
