# Generated by Django 4.2.2 on 2023-07-18 10:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_lectureropinion_opinion_hash_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="lectureropinion",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="webinarparticipantmetadata",
            name="is_mx_valid",
            field=models.CharField(
                choices=[
                    ("NOT_CHECKED", "Nie sprawdzono"),
                    ("INVALID", "MX nie istnieje"),
                    ("VALID", "MX poprawny"),
                ],
                default="NOT_CHECKED",
                max_length=32,
            ),
        ),
    ]
