# Generated by Django 4.2.2 on 2023-06-29 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_webinarparticipantmetadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webinarparticipantmetadata",
            options={},
        ),
    ]
