# Generated by Django 4.2.2 on 2023-06-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_lecturer_slug_alter_webinar_discount_until"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webinar",
            options={
                "ordering": ["date"],
                "verbose_name": "Webinar",
                "verbose_name_plural": "Webinary",
            },
        ),
        migrations.AddField(
            model_name="webinar",
            name="lecturer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.lecturer",
                verbose_name="Wykładowca",
            ),
            preserve_default=False,
        ),
    ]
