# Generated by Django 4.2.2 on 2023-07-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_lectureropinion_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarparticipantmetadata",
            name="clickmeeting_invitation_send",
            field=models.BooleanField(
                default=False, verbose_name="Czy wysłano zaproszenie do clickmeeting?"
            ),
        ),
    ]
