# Generated by Django 4.2.2 on 2023-07-18 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_webinarparticipantmetadata_clickmeeting_invitation_send"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webinar",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
