# Generated by Django 4.2.2 on 2023-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_webinarparticipantmetadata_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail kontaktowy do wykładowcy",
                max_length=254,
                verbose_name="Adres E-mail",
            ),
        ),
    ]
