# Generated by Django 4.2.2 on 2023-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_webinar_options_webinar_lecturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarmetadata",
            name="is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Oznacza termin jako `Termin potwierdzony` na stronie. To czysto kosmetyczna funckja.",
                verbose_name="Termin potwierdzony",
            ),
        ),
        migrations.AddField(
            model_name="webinarmetadata",
            name="remaining_places",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Pozostało miejsc"
            ),
        ),
        migrations.AlterField(
            model_name="webinar",
            name="slug",
            field=models.SlugField(
                help_text="Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)",
                max_length=230,
                unique=True,
                verbose_name="Skrót URL",
            ),
        ),
        migrations.AlterField(
            model_name="webinarmetadata",
            name="auto_send_invoices",
            field=models.BooleanField(
                default=True,
                help_text="Czy po zrealizowanym szkoleniu faktury mają być wysłane automatycznie do wszystkich",
                verbose_name="Automatyczne wysyłanie faktur",
            ),
        ),
        migrations.AlterField(
            model_name="webinarmetadata",
            name="clickmeeting_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ClickMeeting ID"
            ),
        ),
    ]
