# Generated by Django 4.2.2 on 2023-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_webinarmetadata_is_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarmetadata",
            name="remaining_places",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Pozostało miejsc"
            ),
        ),
    ]
