# Generated by Django 4.2.2 on 2023-07-20 11:02

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_webinar_created_at_webinar_updated_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="webinarrecording",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="webinarrecordingtoken",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="webinarapplicationmetadata",
            name="cancellation_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Przyjęto do wiadomości, że szkolenie jest odwołane",
                verbose_name="Przyjęto odwołanie",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplicationmetadata",
            name="token_canceled",
            field=models.UUIDField(
                default=uuid.uuid4, verbose_name="Token odwołania szkolenia"
            ),
        ),
    ]
