# Generated by Django 4.2.2 on 2023-07-20 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_webinarrecording_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplicationmetadata",
            name="token_onopen_canceled",
            field=models.UUIDField(
                default=uuid.uuid4,
                verbose_name="Token odwołania szkolenia (automatyczny)",
            ),
        ),
    ]
