# Generated by Django 4.2.2 on 2023-06-30 13:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_webinareventlog"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="webinarapplication",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="webinarparticipant",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="webinarmetadata",
            name="is_confirmed",
        ),
        migrations.RemoveField(
            model_name="webinarmetadata",
            name="remaining_places",
        ),
        migrations.AddField(
            model_name="webinar",
            name="is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Pokaż `Pewny termin` przy szkoleniu na stronie",
                verbose_name="Pewny termin",
            ),
        ),
        migrations.AddField(
            model_name="webinar",
            name="remaining_places",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Pozostało miejsc"
            ),
        ),
    ]
