# Generated by Django 4.2.2 on 2023-06-19 11:31

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_webinarmetadata_remaining_places"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinar",
            name="program",
            field=django_quill.fields.QuillField(
                default="[Program Szkolenia]", verbose_name="Program szkolenia"
            ),
        ),
    ]
