# Generated by Django 4.2.2 on 2023-06-19 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_webinar_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_price_discounted", models.BooleanField()),
                (
                    "price_netto",
                    models.PositiveSmallIntegerField(verbose_name="Cena NETTO"),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Firma"),
                            ("JSFP", "Firma (Nabywca / Odbiorca)"),
                            ("PRIVATE_PERSON", "Osoba prywatna"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("INVOICE_DIGITAL", "Faktura elektroniczna"),
                            ("INVOICE_PAPER", "Faktura papierowa"),
                        ],
                        default="INVOICE_DIGITAL",
                        max_length=64,
                        verbose_name="Typ faktury",
                    ),
                ),
                (
                    "invoice_email",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail na który zostanie przesłana faktura",
                        max_length=254,
                        verbose_name="E-mail (Faktura)",
                    ),
                ),
                (
                    "invoice_additional_info",
                    models.TextField(
                        max_length=200, verbose_name="Dodatkowe informacje (Faktura)"
                    ),
                ),
                (
                    "vat_exemption",
                    models.CharField(
                        choices=[
                            ("VAT_EXEMPTION_0", "Brak zwolnienia z VAT"),
                            (
                                "VAT_EXEMPTION_13",
                                "Szkolenia zawodowe finansowane ze środków publicznych",
                            ),
                            (
                                "VAT_EXEMPTION_36",
                                "szkolenia zawodowe dofinansowane co najmniej w 70% ze środków publicznych",
                            ),
                        ],
                        default="VAT_EXEMPTION_0",
                        max_length=64,
                    ),
                ),
                (
                    "submitter_first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Imię"),
                ),
                (
                    "submitter_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nazwisko"
                    ),
                ),
                (
                    "submitter_email",
                    models.CharField(blank=True, max_length=100, verbose_name="E-mail"),
                ),
                (
                    "submitter_phone",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numer telefonu"
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(blank=True, verbose_name="Uwagi"),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie",
                "verbose_name_plural": "Zgłoszenia",
            },
        ),
        migrations.CreateModel(
            name="WebinarApplicationCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nip",
                    models.CharField(blank=True, max_length=32, verbose_name="NIP"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=250, verbose_name="Nazwa"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=150, verbose_name="Adres"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Kod pocztowy"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=150, verbose_name="Miasto"),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=150, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Telefon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebinarApplicationMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phoned", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_buyer",
                to="core.webinarapplicationcompany",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_receiver",
                to="core.webinarapplicationcompany",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="webinar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.webinar",
                verbose_name="Webinar",
            ),
        ),
    ]
