# Generated by Django 4.2.2 on 2023-07-21 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_webinarapplicationmetadata_token_onopen_canceled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinarapplicationmetadata",
            name="cancellation_confirmed",
        ),
        migrations.RemoveField(
            model_name="webinarapplicationmetadata",
            name="token_canceled",
        ),
        migrations.RemoveField(
            model_name="webinarapplicationmetadata",
            name="token_onopen_canceled",
        ),
        migrations.CreateModel(
            name="WebinarApplicationCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_open_detected", models.BooleanField(default=False)),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="Token odwołania szkolenia"
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Przyjęto do wiadomości, że szkolenie jest odwołane",
                        verbose_name="Przyjęto odwołanie",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odwołanie szkolenia",
                "verbose_name_plural": "Odwołania szkoleń",
            },
        ),
    ]
