# Generated by Django 4.2.2 on 2023-07-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_webinarapplication_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="profession",
            field=models.CharField(
                blank=True,
                help_text="Widoczna na stronie webinaru pod imieniem i nazwiskiem",
                max_length=40,
                verbose_name="Profesja",
            ),
        ),
        migrations.AddField(
            model_name="webinarmetadata",
            name="lecturer_price_netto",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Cena NETTO wykładowcy"
            ),
        ),
        migrations.CreateModel(
            name="LecturerOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visible_on_page",
                    models.BooleanField(
                        default=False, verbose_name="Widoczna na stronie"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=100, verbose_name="Imię i Nazwisko"),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Firma"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stanowisko"
                    ),
                ),
                ("opinion_text", models.TextField(verbose_name="Treść opinii")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("5stars", "5 gwiazdek"),
                            ("4stars", "4 gwiazdki"),
                            ("3stars", "3 gwiazdki"),
                            ("2stars", "2 gwiazdki"),
                            ("1stars", "1 gwiazdka"),
                        ],
                        max_length=16,
                        verbose_name="Ocena",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.lecturer",
                        verbose_name="Wykładowca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opinia o wykładowcy",
                "verbose_name_plural": "Opinie o wykładowcy",
            },
        ),
    ]
