# Generated by Django 4.2.2 on 2023-06-19 12:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_webinarapplication_webinarapplicationcompany_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarApplicationSubmitter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(max_length=100, verbose_name="Numer telefonu"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="webinarapplication",
            name="is_price_discounted",
        ),
        migrations.RemoveField(
            model_name="webinarapplication",
            name="submitter_email",
        ),
        migrations.RemoveField(
            model_name="webinarapplication",
            name="submitter_first_name",
        ),
        migrations.RemoveField(
            model_name="webinarapplication",
            name="submitter_last_name",
        ),
        migrations.RemoveField(
            model_name="webinarapplication",
            name="submitter_phone",
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Firma"),
                    ("JSFP", "Firma (Nabywca / Odbiorca)"),
                    ("PRIVATE_PERSON", "Osoba prywatna"),
                ],
                max_length=64,
                verbose_name="Typ zgłoszenia",
            ),
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_buyer",
                to="core.webinarapplicationcompany",
                verbose_name="Nabywca",
            ),
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Stworzono"),
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_receiver",
                to="core.webinarapplicationcompany",
                verbose_name="Odbiorca",
            ),
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="Identyfikator zgłoszenia"
            ),
        ),
        migrations.AlterField(
            model_name="webinarapplication",
            name="vat_exemption",
            field=models.CharField(
                choices=[
                    ("VAT_EXEMPTION_0", "Brak zwolnienia z VAT"),
                    (
                        "VAT_EXEMPTION_13",
                        "Szkolenia zawodowe finansowane ze środków publicznych",
                    ),
                    (
                        "VAT_EXEMPTION_36",
                        "szkolenia zawodowe dofinansowane co najmniej w 70% ze środków publicznych",
                    ),
                ],
                default="VAT_EXEMPTION_0",
                max_length=64,
                verbose_name="Zwolnienie z VAT",
            ),
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_submitter",
                to="core.webinarapplicationsubmitter",
                verbose_name="Osoba zgłaszająca",
            ),
        ),
    ]
