# Generated by Django 4.2.2 on 2023-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_lecturer_profession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="visible_on_page",
            field=models.BooleanField(
                default=True,
                help_text="Czy wykładowca ma być widoczny na stronie",
                verbose_name="Widoczny na stronie",
            ),
        ),
    ]
