# Generated by Django 4.2.2 on 2023-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0015_remove_webinarapplicationmetadata_cancellation_confirmed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplicationcancellation",
            name="clicked_in_link",
            field=models.BooleanField(default=False),
        ),
    ]
