# Generated by Django 4.2.2 on 2023-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_webinarapplicationcancellation_clicked_in_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarapplicationcancellation",
            name="clicked_in_link",
            field=models.BooleanField(default=False, verbose_name="Kliknięto w link"),
        ),
        migrations.AlterField(
            model_name="webinarapplicationcancellation",
            name="email_open_detected",
            field=models.BooleanField(
                default=False, verbose_name="Wykryto otwarcie wiadomości e-mail"
            ),
        ),
    ]
