# Generated by Django 4.2.2 on 2023-07-02 11:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_lecturer_visible_on_page"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="lecturer",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="lectureropinion",
            name="rating",
            field=models.CharField(
                choices=[
                    ("1stars", "1 gwiazdka"),
                    ("2stars", "2 gwiazdki"),
                    ("3stars", "3 gwiazdki"),
                    ("4stars", "4 gwiazdki"),
                    ("5stars", "5 gwiazdek"),
                ],
                max_length=16,
                verbose_name="Ocena",
            ),
        ),
    ]
