# Generated by Django 4.2.2 on 2023-06-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_webinarapplicationsubmitter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplication",
            name="discount_applied",
            field=models.BooleanField(default=False, verbose_name="Promocja nałożona"),
        ),
    ]
