# Generated by Django 4.2.2 on 2023-07-04 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_lecturer_managers_alter_lectureropinion_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Identyfikator zgłoszenia",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                ("title", models.TextField(verbose_name="Tytuł szkolenia")),
                ("issue_date", models.DateField(verbose_name="Data wystawienia")),
                (
                    "hours",
                    models.CharField(
                        help_text="Przykład: `4 godziny`",
                        max_length=20,
                        verbose_name="Czas trwania",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certyfikat",
                "verbose_name_plural": "Certyfikaty",
            },
        ),
    ]
