# Generated by Django 4.2.2 on 2023-06-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_webinarapplication_discount_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarapplication",
            name="invoice_additional_info",
            field=models.TextField(
                blank=True,
                max_length=200,
                verbose_name="Dodatkowe informacje (Faktura)",
            ),
        ),
    ]
