# Generated by Django 4.2.2 on 2023-07-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_webinarapplicationcancellation_clicked_in_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplicationcancellation",
            name="discount_code",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Kod rabatowy"
            ),
        ),
    ]
