# Generated by Django 4.2.2 on 2023-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_webinarapplication_invoice_additional_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarapplication",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Firma"),
                    ("JSFP", "Firma (Nabywca / Odbiorca)"),
                    ("PRIVATE_PERSON", "Osoba prywatna"),
                ],
                default="COMPANY",
                max_length=64,
                verbose_name="Typ zgłoszenia",
            ),
        ),
    ]
