# Generated by Django 4.2.2 on 2023-07-23 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_webinarapplicationcancellation_discount_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarMoveRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_datetime",
                    models.DateTimeField(verbose_name="Początkowy termin"),
                ),
                ("to_datetime", models.DateTimeField(verbose_name="Docelowy termin")),
                (
                    "participants_count",
                    models.PositiveSmallIntegerField(
                        help_text="Ilość uczestników w momencie przenoszenia",
                        verbose_name="Ilość uczestników",
                    ),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przeniesiony termin",
                "verbose_name_plural": "Przeniesione terminy",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebinarMoveRegisterItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="Token odwołania szkolenia"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INIT", "Wysłano zapytanie"),
                            ("ACCEPTED", "Akceptuje"),
                            ("ACCEPTED_WITH_DISCOUNT", "Akceptuje (zniżka)"),
                            ("RESIGNATION", "Rezygnacja"),
                        ],
                        default="INIT",
                        max_length=32,
                    ),
                ),
                (
                    "email_open_detected",
                    models.BooleanField(
                        default=False, verbose_name="Wykryto otwarcie wiadomości e-mail"
                    ),
                ),
                (
                    "clicked_accept_link",
                    models.BooleanField(
                        default=False, verbose_name="Kliknięto w przycisk 'Akceptuję'"
                    ),
                ),
                (
                    "clicked_resignation_link",
                    models.BooleanField(
                        default=False, verbose_name="Kliknięto w przycisk 'Rezygnuję'"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                        verbose_name="Zgłoszenie",
                    ),
                ),
                (
                    "move_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarmoveregister",
                        verbose_name="Rejestr przeniesień szkolenia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przeniesione zgłoszenie",
                "verbose_name_plural": "Przeniesione zgłoszenia",
            },
        ),
    ]
