# Generated by Django 4.2.2 on 2023-07-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_webinarcertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarcertificate",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.webinarparticipant",
                verbose_name="Uczestnik",
            ),
        ),
    ]
