# Generated by Django 4.2.2 on 2023-07-23 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_webinarmoveregister_webinarmoveregisteritem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webinarmoveregister",
            old_name="participants_count",
            new_name="applications_count",
        ),
    ]
