# Generated by Django 4.2.2 on 2023-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_webinarapplication_application_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("INIT", "Zgłoszenie rozpoczęte"),
                    ("SENT", "Zgłoszenie wysłane"),
                ],
                default="INIT",
                max_length=32,
            ),
        ),
    ]
