# Generated by Django 4.2.2 on 2023-07-04 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_webinarcertificate_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarcertificate",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                verbose_name="Identyfikator certyfikatu",
            ),
        ),
    ]
