# Generated by Django 4.2.2 on 2023-06-19 16:10

import django.db.models.manager
from django.db import migrations, models

import core.models.webinar_model


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_webinarapplication_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="webinar",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="webinar",
            name="random_int",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
