# Generated by Django 4.2.2 on 2023-07-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_webinarcertificate_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eventlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title_html",
                    models.CharField(max_length=350, verbose_name="Tytuł (HTML)"),
                ),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="Treść (HTML)"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=32, verbose_name="Ikona"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=32, verbose_name="Kolor"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarapplication",
                        verbose_name="Zgłoszenie",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarparticipant",
                        verbose_name="Uczestnik",
                    ),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WebinarEventlog",
        ),
    ]
