# Generated by Django 4.2.2 on 2023-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_webinar_managers_webinar_random_int"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="description",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
