# Generated by Django 4.2.2 on 2023-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_loyaltyprogram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountapplicationapplied",
            name="discount_weight",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Pole używane do ograniczenia liczby nałożonych rabatów",
                verbose_name="Waga rabatu",
            ),
        ),
    ]
