# Generated by Django 4.2.2 on 2023-07-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_eventlog_delete_webinareventlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinarapplication",
            name="receiver",
        ),
        migrations.AddField(
            model_name="webinarapplication",
            name="recipient",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_recipient",
                to="core.webinarapplicationcompany",
                verbose_name="Odbiorca",
            ),
        ),
    ]
