# Generated by Django 4.2.2 on 2023-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_discountapplicationapplied_discount_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="recording_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Wykładowca zgadza się na nagranie z tego szkolenia",
                verbose_name="Nagrania dostępne",
            ),
        ),
    ]
