# Generated by Django 4.2.2 on 2023-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_webinar_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinar",
            name="random_int",
        ),
        migrations.AlterField(
            model_name="webinar",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Dodatkowy opis webinaru",
                max_length=200,
                verbose_name="Dodatkowy opis",
            ),
        ),
    ]
