# Generated by Django 4.2.2 on 2023-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_remove_webinar_random_int_alter_webinar_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="title_original",
            field=models.TextField(
                default="Placeholder",
                help_text="Tytuł szkolenia jaki został dostarczony przez wykładowce",
                verbose_name="Pełny tytuł szkolenia",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="webinar",
            name="title",
            field=models.TextField(
                help_text="Tytuł szkolenia zmodyfikowany, aby mieścił się w ogrniczonej ilości znaków",
                max_length=220,
                verbose_name="Tytuł szkolenia",
            ),
        ),
    ]
