# Generated by Django 4.2.2 on 2023-07-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_webinarapplication_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="title_html",
            field=models.TextField(verbose_name="Tytuł (HTML)"),
        ),
    ]
