# Generated by Django 4.2.2 on 2023-07-05 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_eventlog_title_html"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventlog",
            options={"ordering": ["-created_at"]},
        ),
    ]
