# Generated by Django 4.2.2 on 2023-06-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_webinar_title_original_alter_webinar_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarcategory",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
