# Generated by Django 4.2.2 on 2023-08-02 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_webinarapplicationmetadata_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token",
            field=models.UUIDField(
                default=uuid.uuid4, verbose_name="Token aktywacyjny"
            ),
        ),
    ]
