# Generated by Django 4.2.2 on 2023-08-03 10:32

import core.models.blacklist.blacklisted_email_temporary_model
import core.models.mailing.mailing_campaign_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_user_activation_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedDomain",
            fields=[
                (
                    "domain",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Domena",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zablokowana domena",
                "verbose_name_plural": "Zablokowane domeny",
            },
        ),
        migrations.CreateModel(
            name="BlacklistedEmail",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Adres E-mail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zablokowany e-mail",
                "verbose_name_plural": "Zablokowane e-maile",
            },
        ),
        migrations.CreateModel(
            name="BlacklistedEmailTemporary",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Adres E-mail",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=core.models.blacklist.blacklisted_email_temporary_model.default_expires_at,
                        help_text="Kiedy zablokowanie wygasa",
                        verbose_name="Wygasa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zablokowane tymczasowo emaile",
                "verbose_name_plural": "Zablokowane tymczasowo email",
            },
        ),
        migrations.CreateModel(
            name="BlacklistedPhrase",
            fields=[
                (
                    "phrase",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Fraza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zablokowana fraza",
                "verbose_name_plural": "Zablokowane frazy",
            },
        ),
        migrations.CreateModel(
            name="BlacklistedPrefix",
            fields=[
                (
                    "prefix",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Prefiks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zablokowany prefix",
                "verbose_name_plural": "Zablokowane prefixy",
            },
        ),
        migrations.CreateModel(
            name="MailingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa szablonu"),
                ),
                ("html", models.TextField(verbose_name="HTML")),
                ("text", models.TextField(blank=True, verbose_name="TEXT")),
            ],
            options={
                "verbose_name": "Szablon mailingowy",
                "verbose_name_plural": "Szablony mailingowe",
            },
        ),
        migrations.CreateModel(
            name="SmtpSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.EmailField(max_length=254, verbose_name="Nazwa użytkownika"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Hasło")),
                (
                    "incoming_server_hostname",
                    models.CharField(
                        max_length=255, verbose_name="Serwer przychodzący Host"
                    ),
                ),
                (
                    "incoming_server_port",
                    models.CharField(
                        choices=[("995", "995")],
                        max_length=5,
                        verbose_name="Serwer przychodzący Port",
                    ),
                ),
                (
                    "outgoing_server_hostname",
                    models.CharField(
                        max_length=255, verbose_name="Serwer wychodzący Host"
                    ),
                ),
                (
                    "outgoing_server_port",
                    models.CharField(
                        choices=[("465", "465")],
                        max_length=5,
                        verbose_name="Serwer wychodzący Port",
                    ),
                ),
                ("domain", models.CharField(max_length=100, verbose_name="Domena")),
                ("ssl", models.BooleanField(default=False, verbose_name="SSL")),
                (
                    "reply_to",
                    models.EmailField(max_length=254, verbose_name="Reply-To"),
                ),
            ],
            options={
                "verbose_name": "Konto wysyłkowe",
                "verbose_name_plural": "Konta wysyłkowe",
            },
        ),
        migrations.CreateModel(
            name="MailingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Tytuł kampanii"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAUSED", "Paused"),
                            ("SENDING", "Sending"),
                            ("DONE", "Done"),
                        ],
                        default="PAUSED",
                        max_length=32,
                    ),
                ),
                (
                    "allowed_to_send_after",
                    models.TimeField(
                        default=core.models.mailing.mailing_campaign_model.default_allowed_to_send_after,
                        verbose_name="Wysyłaj po",
                    ),
                ),
                (
                    "allowed_to_send_before",
                    models.TimeField(
                        default=core.models.mailing.mailing_campaign_model.default_allowed_to_send_before,
                        verbose_name="Wysyłaj do",
                    ),
                ),
                ("subjects", models.TextField(verbose_name="Tytuły wiadomości e-mail")),
                ("alias", models.CharField(max_length=64, verbose_name="Alias")),
                ("monday", models.BooleanField(default=True)),
                ("tuesday", models.BooleanField(default=True)),
                ("wednesday", models.BooleanField(default=True)),
                ("thursday", models.BooleanField(default=True)),
                ("friday", models.BooleanField(default=True)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                (
                    "smtp_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.smtpsender",
                        verbose_name="Konto wysyłkowe",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.mailingtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailing Kampania",
                "verbose_name_plural": "Mailing Kampanie",
            },
        ),
    ]
