# Generated by Django 4.2.2 on 2023-06-20 09:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_webinarcategory_visible"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="webinarcategory",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="webinarcategory",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="Widoczna na stronie"),
        ),
    ]
