# Generated by Django 4.2.2 on 2023-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_webinarcategory_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarapplication",
            name="vat_exemption",
            field=models.CharField(
                choices=[
                    ("VAT_EXEMPTION_0", "Brak zwolnienia z VAT"),
                    (
                        "VAT_EXEMPTION_13",
                        "Szkolenia zawodowe finansowane ze środków publicznych",
                    ),
                    (
                        "VAT_EXEMPTION_36",
                        "Szkolenia zawodowe dofinansowane co najmniej w 70% ze środków publicznych",
                    ),
                ],
                default="VAT_EXEMPTION_0",
                max_length=64,
                verbose_name="Zwolnienie z VAT",
            ),
        ),
        migrations.AlterField(
            model_name="webinarapplicationcompany",
            name="address",
            field=models.CharField(max_length=150, verbose_name="Adres"),
        ),
        migrations.AlterField(
            model_name="webinarapplicationcompany",
            name="city",
            field=models.CharField(max_length=150, verbose_name="Miasto"),
        ),
        migrations.AlterField(
            model_name="webinarapplicationcompany",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Nazwa"),
        ),
        migrations.AlterField(
            model_name="webinarapplicationcompany",
            name="nip",
            field=models.CharField(max_length=32, verbose_name="NIP"),
        ),
        migrations.AlterField(
            model_name="webinarapplicationcompany",
            name="postal_code",
            field=models.CharField(max_length=16, verbose_name="Kod pocztowy"),
        ),
    ]
