# Generated by Django 4.2.2 on 2023-07-06 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_eventlog_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinarparticipantmetadata",
            name="confirmation_email_opened",
        ),
        migrations.AlterField(
            model_name="webinarparticipantmetadata",
            name="phoned",
            field=models.BooleanField(
                default=False, verbose_name="Czy zadzwoniono przed szkoleniem?"
            ),
        ),
        migrations.CreateModel(
            name="WebinarAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filename",
                    models.CharField(max_length=300, verbose_name="Nazwa pliku"),
                ),
                (
                    "filesize",
                    models.CharField(max_length=80, verbose_name="Rozmiar pliku"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="Typ MIME"),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materiał szkoleniowy",
                "verbose_name_plural": "Materiały szkoleniowe",
                "ordering": ["-created_at"],
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
