# Generated by Django 4.2.2 on 2023-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_loyaltyprogramincome_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltyprogram",
            name="provision_percent",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Prowizja (%)"
            ),
        ),
    ]
