# Generated by Django 4.2.2 on 2023-07-06 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0027_remove_webinarparticipantmetadata_confirmation_email_opened_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarmetadata",
            name="assets_token",
            field=models.UUIDField(
                default=uuid.uuid4, verbose_name="Token dostępu do materiałów"
            ),
        ),
    ]
