# Generated by Django 4.2.2 on 2023-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_webinarapplication_vat_exemption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplicationsubmitter",
            name="is_participant",
            field=models.BooleanField(
                default=False, verbose_name="Jest też uczestnikiem"
            ),
        ),
    ]
