# Generated by Django 4.2.2 on 2023-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_webinarmetadata_assets_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarasset",
            name="file",
            field=models.FileField(default="", upload_to="", verbose_name="Plik"),
            preserve_default=False,
        ),
    ]
