# Generated by Django 4.2.2 on 2023-08-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_loyaltyprogram_provision_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinar",
            name="status",
            field=models.CharField(
                choices=[
                    ("INIT", "Planowany termin"),
                    ("CONFIRMED", "Termin potwierdzony"),
                    ("CANCELED", "Termin odwołany"),
                    ("DONE", "Termin zrealizowany"),
                ],
                default="INIT",
                max_length=32,
            ),
        ),
    ]
