# Generated by Django 4.2.2 on 2023-07-06 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_webinarasset_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webinarasset",
            old_name="mime_type",
            new_name="content_type",
        ),
    ]
