# Generated by Django 4.2.2 on 2023-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_rename_mime_type_webinarasset_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarasset",
            name="file",
            field=models.FileField(
                upload_to="uploads/webinar_assets", verbose_name="Plik"
            ),
        ),
    ]
