# Generated by Django 4.2.2 on 2023-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_alter_mailingcampaign_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarcategory",
            name="icon_html",
            field=models.TextField(blank=True, verbose_name="Ikona HTML"),
        ),
        migrations.AddField(
            model_name="webinarcategory",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Krótki opis"
            ),
        ),
    ]
