# Generated by Django 4.2.2 on 2023-07-07 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_webinarasset_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarRecording",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Pokaż nagranie na stronie",
                        verbose_name="Widoczne na stronie",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DOWNLOADING", "W trakcie pobieranie nagrania"),
                            ("DOWNLOADED", "Pobrano nagranie"),
                            ("FAILED", "Wystąpił błąd podczas pobierania"),
                        ],
                        default="DOWNLOADING",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "recording_id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID nagrania",
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(verbose_name="URL do pobrania nagrania"),
                ),
                (
                    "recording_duration_seconds",
                    models.PositiveIntegerField(
                        verbose_name="Czas trwania nagrania (sekundy)"
                    ),
                ),
                (
                    "recorder_started",
                    models.DateTimeField(verbose_name="Kiedy rozpoczęto nagrywanie"),
                ),
                (
                    "recording_file_size",
                    models.CharField(max_length=64, verbose_name="Rozmiar nagrania"),
                ),
                (
                    "recording_name",
                    models.CharField(max_length=500, verbose_name="Nazwa nagrania"),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinar",
                        verbose_name="Webinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nagranie",
                "verbose_name_plural": "Nagrania",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebinarRecordingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Token nagrania"
                    ),
                ),
                (
                    "deny_access",
                    models.BooleanField(
                        default=True,
                        help_text="Zaznacz aby odmówić dostępu do nagrania przez ten token",
                        verbose_name="Odmówiono dostępu",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Puste pole oznacza, że token nie wygasa nigdy",
                        null=True,
                        verbose_name="Token wygasa",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarparticipant",
                        verbose_name="Uczestnik",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.webinarrecording",
                        verbose_name="Nagranie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token nagrania",
                "verbose_name_plural": "Tokeny nagrań",
                "ordering": ["-created_at"],
            },
        ),
    ]
