# Generated by Django 4.2.2 on 2023-07-07 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_webinarrecording_webinarrecordingtoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webinarrecordingtoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Nagranie (token)",
                "verbose_name_plural": "Nagrania (tokeny)",
            },
        ),
    ]
