# Generated by Django 4.2.2 on 2023-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_webinarrecordingtoken_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarrecording",
            name="status",
            field=models.CharField(
                choices=[
                    ("DOWNLOADING", "W trakcie pobierania nagrania"),
                    ("DOWNLOADED", "Pobrano nagranie"),
                    ("FAILED", "Wystąpił błąd podczas pobierania"),
                ],
                default="DOWNLOADING",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
