# Generated by Django 4.2.2 on 2023-08-29 13:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_lecturer_fake_stat_participants_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=64, verbose_name="Imię")),
                ("last_name", models.CharField(max_length=64, verbose_name="Nazwisko")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adres e-mail"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Numer telefonu"
                    ),
                ),
                ("message", models.TextField(verbose_name="Wiadomość")),
                (
                    "related_to",
                    models.CharField(
                        blank=True, max_length=264, verbose_name="Nawiązuje do"
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiadomość kontaktowa",
                "verbose_name_plural": "Wiadomość kontaktowa",
                "ordering": ["-created_at"],
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
