# Generated by Django 4.2.2 on 2023-08-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("PARTICIPATING", "Uczestniczy w szkoleniu"),
                    ("RESIGNATION", "Rezygnacja ze szkolenia"),
                ],
                default="PARTICIPATING",
                max_length=32,
            ),
        ),
    ]
