# Generated by Django 4.2.2 on 2023-09-02 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_webinarparticipant_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lectureropinion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Opinia o wykładowcy",
                "verbose_name_plural": "Opinie o wykładowcy",
            },
        ),
    ]
