# Generated by Django 4.2.2 on 2023-09-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_lectureropinion_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(max_length=1000, verbose_name="Wiadomość"),
        ),
    ]
