# Generated by Django 4.2.2 on 2023-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_contactmessage_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarcategory",
            name="about_html",
            field=models.TextField(
                default="[Opis kategorii]", verbose_name="Opis kategorii"
            ),
        ),
    ]
