# Generated by Django 4.2.2 on 2023-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_mailingcampaign_stat_procesed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarapplicationsubmitter",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Imię"),
        ),
        migrations.AlterField(
            model_name="webinarapplicationsubmitter",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Nazwisko"),
        ),
    ]
