# Generated by Django 4.2.2 on 2023-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_blacklisteddomain_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="order_value",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Wartość sortująca"
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="visible_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Czy wykładowca ma być widoczny na stronie głównej",
                verbose_name="Widoczny na stronie głównej",
            ),
        ),
    ]
