# Generated by Django 4.2.2 on 2023-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_lecturer_order_value_lecturer_visible_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarmetadata",
            name="click_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Kliknięcia"),
        ),
    ]
