# Generated by Django 4.2.2 on 2023-10-06 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_webinarmetadata_click_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webinarmetadata",
            old_name="click_count",
            new_name="click_count_mailing",
        ),
    ]
