# Generated by Django 4.2.2 on 2023-10-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_webinar_discount_netto"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="grouping_token",
            field=models.CharField(
                blank=True,
                help_text="Ciąg znaków grupujący razem terminy",
                max_length=32,
                verbose_name="Token grupujący",
            ),
        ),
    ]
