# Generated by Django 4.2.2 on 2023-10-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_webinar_is_fake_alter_webinar_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarmetadata",
            name="click_count_onesignal",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Kliknięcia Onesignal"
            ),
        ),
    ]
