# Generated by Django 4.2.2 on 2023-10-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_webinarmetadata_click_count_onesignal"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmcompany",
            name="is_nonpaying",
            field=models.BooleanField(
                default=False,
                help_text="Ten klient nie zapłacił za fakturę w przeszłości",
                verbose_name="Niepłacący",
            ),
        ),
        migrations.AddField(
            model_name="crmcompany",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notatki"),
        ),
    ]
