# Generated by Django 4.2.2 on 2023-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_crmcompany_is_nonpaying_crmcompany_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="is_hidden",
            field=models.BooleanField(
                default=False, verbose_name="Ukryj termin szkolenia"
            ),
        ),
    ]
