# Generated by Django 4.2.2 on 2023-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_webinar_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="facebook_post_image",
            field=models.ImageField(
                blank=True,
                help_text="wymiary: 1200px na 630px",
                upload_to="uploads/webinar-facebook-covers",
                verbose_name="Facebook Post Image",
            ),
        ),
    ]
