# Generated by Django 4.2.2 on 2023-11-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_webinar_facebook_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarrecordingtoken",
            name="free_access",
            field=models.BooleanField(
                default=False,
                help_text="To nagranie jest dostępne dla każdego kto ma link",
                verbose_name="Otwarty dostęp",
            ),
        ),
        migrations.AddField(
            model_name="webinarrecordingtoken",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="To nagranie jest zabezpieczone hasłem",
                max_length=64,
                verbose_name="Hasło",
            ),
        ),
    ]
