# Generated by Django 4.2.2 on 2023-11-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_webinarrecordingtoken_free_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountapplicationapplied",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.webinarapplication",
                verbose_name="Zgłoszenie",
            ),
        ),
    ]
