# Generated by Django 4.2.2 on 2023-11-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_discountapplicationapplied_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="agrees_to_recording",
            field=models.BooleanField(
                default=True,
                help_text="Czy wykładowca zgadza się na nagrania",
                verbose_name="Zgadza się na nagrania",
            ),
        ),
    ]
