# Generated by Django 4.2.2 on 2023-11-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_lecturer_agrees_to_recording"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingcampaign",
            name="webinar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.webinar",
                verbose_name="Szkolenie",
            ),
        ),
    ]
