# Generated by Django 4.2.2 on 2023-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_mailingcampaign_webinar"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingcampaign",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Komentarz"),
        ),
    ]
