# Generated by Django 4.2.2 on 2023-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_mailingcampaign_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinarapplication",
            name="got_to_summary",
            field=models.BooleanField(
                default=False,
                help_text="Czy zgłaszający dotarł do strony podsumowania?",
                verbose_name="Dotarł do podsumowania",
            ),
        ),
    ]
