# Generated by Django 4.2.2 on 2023-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_webinarapplication_got_to_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="very_short_biography",
            field=models.TextField(blank=True, verbose_name="Bardzo krótka biografia"),
        ),
    ]
