# Generated by Django 4.2.2 on 2023-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_lecturer_very_short_biography"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinarmetadata",
            name="auto_send_invoices",
        ),
        migrations.AlterField(
            model_name="webinarapplicationinvoice",
            name="vat_exemption",
            field=models.CharField(
                choices=[
                    ("VAT_EXEMPTION_0", "Brak zwolnienia z VAT"),
                    (
                        "VAT_EXEMPTION_13",
                        "Szkolenia zawodowe finansowane w całości ze środków publicznych - art. 43. ust. 1 pkt 29 lit. c",
                    ),
                    (
                        "VAT_EXEMPTION_36",
                        "Szkolenia zawodowe dofinansowane co najmniej w 70% ze środków publicznych - par. 3. ust. 1 pkt 14",
                    ),
                    (
                        "VAT_EXEMPTION_113",
                        "Faktura wystawiana bez podatku VAT na podstawie art. 113 ust. 1 i 9 ustawy o VAT",
                    ),
                ],
                default="VAT_EXEMPTION_0",
                max_length=64,
                verbose_name="Zwolnienie z VAT",
            ),
        ),
    ]
