# Generated by Django 4.2.2 on 2023-12-07 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_remove_webinarmetadata_auto_send_invoices_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="webinar",
            old_name="program_enchanted",
            new_name="program_pretty",
        ),
    ]
