# Generated by Django 4.2.2 on 2023-12-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_rename_program_enchanted_webinar_program_pretty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarapplicationinvoice",
            name="invoice_additional_info",
            field=models.TextField(
                blank=True,
                max_length=200,
                verbose_name="Dodatkowe informacje widoczne na Fakturze",
            ),
        ),
    ]
