# Generated by Django 4.2.2 on 2023-12-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_remove_webinarcategory_is_homepage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webinarcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Kategoria nadrzędna",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.webinarcategory",
                verbose_name="Rodzic",
            ),
        ),
    ]
