# Generated by Django 4.2.2 on 2023-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_categorytrustedus"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytrustedus",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Im niższa wartość tym wyższa pozycja kategorii przy wyświetlaniu",
                verbose_name="Pozycja",
            ),
        ),
        migrations.AddField(
            model_name="lectureropinion",
            name="added_on_website",
            field=models.BooleanField(
                default=False, verbose_name="Dodana przez stronę"
            ),
        ),
        migrations.AlterField(
            model_name="lectureropinion",
            name="visible_on_page",
            field=models.BooleanField(
                default=False, verbose_name="Widoczna na stronie (Zatwierdzona)"
            ),
        ),
    ]
