# Generated by Django 4.2.2 on 2023-12-09 12:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_categorytrustedus_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistAggressor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Adres E-mail",
                    ),
                ),
                (
                    "message_content",
                    models.TextField(blank=True, verbose_name="Treść wiadomości"),
                ),
                (
                    "trigger_content",
                    models.TextField(
                        blank=True, verbose_name="Co spowodowało wykrycie?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zablokowany e-mail (agresor)",
                "verbose_name_plural": "Zablokowane e-maile (agresor)",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistPleading",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Adres E-mail",
                    ),
                ),
                (
                    "message_content",
                    models.TextField(blank=True, verbose_name="Treść wiadomości"),
                ),
                (
                    "trigger_content",
                    models.TextField(
                        blank=True, verbose_name="Co spowodowało wykrycie?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zablokowany e-mail (agresor)",
                "verbose_name_plural": "Zablokowane e-maile (agresor)",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklisteddomain",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklistedemail",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklistedemailtemporary",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklistedphrase",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklistedprefix",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
