# Generated by Django 4.2.2 on 2023-12-09 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_blacklistaggressor_blacklistpleading_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blacklistpleading",
            options={
                "verbose_name": "Zablokowany e-mail (prośba)",
                "verbose_name_plural": "Zablokowane e-maile (prośba)",
            },
        ),
    ]
