# Generated by Django 4.2.2 on 2023-12-11 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_alter_blacklistpleading_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=230, verbose_name="Nazwa cyklu")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Slug (SEO)",
                        max_length=230,
                        unique=True,
                        verbose_name="Skrót URL",
                    ),
                ),
                ("html", models.TextField(blank=True, verbose_name="Treść HTML")),
                (
                    "categories",
                    models.ManyToManyField(
                        to="core.webinarcategory", verbose_name="Kategorie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Konferencja (cykl)",
                "verbose_name_plural": "Konferencje (cykl)",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConferenceEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=230, verbose_name="Nazwa edycji")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Slug (SEO)",
                        max_length=230,
                        unique=True,
                        verbose_name="Skrót URL",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Data i Godzina")),
                ("html", models.TextField(blank=True, verbose_name="Treść HTML")),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.conferencecycle",
                        verbose_name="Konferencja (cykl)",
                    ),
                ),
                (
                    "webinar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.webinar",
                        verbose_name="Webinar (płatny dostęp)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konferencja (edycja)",
                "verbose_name_plural": "Konferencje (edycja)",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConferenceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=230, verbose_name="Tytuł wpisu")),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Krótki opis"),
                ),
                ("hour_from", models.TimeField(verbose_name="Godzina do")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Slug (SEO)",
                        max_length=230,
                        unique=True,
                        verbose_name="Skrót URL",
                    ),
                ),
                ("html", models.TextField(blank=True, verbose_name="Treść HTML")),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.conferenceedition",
                        verbose_name="Edycja",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.lecturer",
                        verbose_name="Wykładowca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konferencja (harmonogram)",
                "verbose_name_plural": "Konferencje (harmonogram)",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
