# Generated by Django 4.2.2 on 2023-12-11 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_conferencecycle_conferenceedition_conferenceschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceschedule",
            name="hour_to",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Godzina do"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conferenceschedule",
            name="hour_from",
            field=models.TimeField(verbose_name="Godzina od"),
        ),
    ]
