# Generated by Django 4.2.2 on 2023-12-11 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_conferenceschedule_hour_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conferenceschedule",
            name="slug",
        ),
    ]
