# Generated by Django 4.2.2 on 2023-12-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_remove_conferenceschedule_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferencecycle",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Krótki opis widoczny pod nazwą cyklu",
                verbose_name="Krótki opis",
            ),
        ),
    ]
