# Generated by Django 4.2.2 on 2023-12-11 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_conferencecycle_short_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conferenceedition",
            old_name="date",
            new_name="date_from",
        ),
    ]
