# Generated by Django 4.2.2 on 2023-12-11 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_rename_date_conferenceedition_date_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceedition",
            name="date_to",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data i Godzina (stop)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conferenceedition",
            name="date_from",
            field=models.DateTimeField(verbose_name="Data i Godzina (start)"),
        ),
    ]
