# Generated by Django 4.2.2 on 2023-12-12 10:16

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_conferenceedition_date_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Adres E-mail",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Imię"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nazwisko"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Telefon"),
                ),
                (
                    "is_subscribed",
                    models.BooleanField(default=False, verbose_name="Czy subskrybuje?"),
                ),
                (
                    "was_customer",
                    models.BooleanField(
                        default=False, verbose_name="Czy był klientem?"
                    ),
                ),
                (
                    "detected_bot_click",
                    models.BooleanField(
                        default=False, verbose_name="Wykryto kliknięcie bota?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_SPECIFIED", "Ogólnie zainteresowany"),
                            ("WEBINAR_PARTICIPANT", "Zgłoszenie - uczestnik webinaru"),
                            ("WEBINAR_CONTACT", "Zgłoszenie -  kontakt ogólny"),
                            ("NEWSLETTER_FOOTER", "Stopka - Zapis do newslettera"),
                            ("CONFERENCE_FREE", "Konferencja - uczestnik darmowy"),
                            ("CONFERENCE_PAID", "Konferencja - uczestnik płatny"),
                            (
                                "EMAIL_MESSAGE_SIGNUP",
                                "E-mail - poprosił od zapis przez e-mail",
                            ),
                        ],
                        max_length=32,
                        verbose_name="Źródło lead'a",
                    ),
                ),
                (
                    "preferences_token",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="Token panelu preferencij"
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, verbose_name="Token wypisu"),
                ),
                ("singup_ip_address", models.CharField(blank=True, max_length=64)),
                (
                    "last_email_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ostatnio wysłana wiadomość e-mail",
                        null=True,
                    ),
                ),
                (
                    "last_email_opened",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ostatnio otwarto wiadomość e-mail",
                        null=True,
                    ),
                ),
                (
                    "last_email_clicked",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ostatnio kliknięto w wiadomość e-mail",
                        null=True,
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ostatnio dokonano zakupu na stronie",
                        null=True,
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ostatnia jakaklowiek aktywność",
                        null=True,
                    ),
                ),
                (
                    "conferences",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Na jakie konferencje się zapisał?",
                        to="core.conferenceedition",
                        verbose_name="Konferencje",
                    ),
                ),
                (
                    "preferences",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Jakimi kategoriami jest zainteresowany?",
                        to="core.webinarcategory",
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "webinars",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Na jakie webinary go zapisano?",
                        to="core.webinar",
                        verbose_name="Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead (Główny)",
                "verbose_name_plural": "Lead'y (Główne)",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
