# Generated by Django 4.2.2 on 2023-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_leadmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadmodel",
            name="webinars",
            field=models.ManyToManyField(
                blank=True,
                help_text="Na jakie webinary go zapisano?",
                to="core.webinar",
                verbose_name="Webinary",
            ),
        ),
    ]
