# Generated by Django 4.2.2 on 2023-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_alter_leadmodel_webinars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_SPECIFIED", "Ogólnie zainteresowany"),
                    ("WEBINAR_PARTICIPANT", "Zgłoszenie - uczestnik webinaru"),
                    ("WEBINAR_CONTACT", "Zgłoszenie -  kontakt ogólny"),
                    ("NEWSLETTER_FOOTER", "Stopka - Zapis do newslettera"),
                    ("CONFERENCE_FREE", "Konferencja - uczestnik darmowy"),
                    ("CONFERENCE_PAID", "Konferencja - uczestnik płatny"),
                    ("EMAIL_MESSAGE_SIGNUP", "E-mail - poprosił od zapis przez e-mail"),
                ],
                default="NOT_SPECIFIED",
                max_length=32,
                verbose_name="Źródło lead'a",
            ),
        ),
    ]
