# Generated by Django 4.2.2 on 2023-12-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_alter_leadmodel_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leadmodel",
            old_name="status",
            new_name="lead_source",
        ),
        migrations.AddField(
            model_name="leadmodel",
            name="was_activated",
            field=models.BooleanField(
                default=False, verbose_name="Czy aktywował przez e-mail?"
            ),
        ),
    ]
