# Generated by Django 4.2.2 on 2023-12-12 14:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_rename_status_leadmodel_lead_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("301", "Moved Permanently"),
                            ("307", "Temporary Redirect"),
                            ("308", "Permanent Redirect"),
                        ],
                        max_length=10,
                        verbose_name="Status code",
                    ),
                ),
                (
                    "counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Redirect counter"
                    ),
                ),
            ],
            options={
                "verbose_name": "Przekierowanie (manualne)",
                "verbose_name_plural": "Przekierowania (manualne)",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="crmtodo",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
