# Generated by Django 4.2.2 on 2023-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_redirectmanual_alter_crmtodo_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirectmanual",
            name="slug",
            field=models.CharField(
                default="/placeholder/", max_length=350, verbose_name="Slug"
            ),
            preserve_default=False,
        ),
    ]
