# Generated by Django 4.2.2 on 2023-12-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_redirectmanual_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirectmanual",
            name="url",
            field=models.CharField(max_length=350, verbose_name="URL"),
        ),
    ]
