# Generated by Django 4.2.2 on 2023-12-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_alter_redirectmanual_status_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redirectmanual",
            name="id",
        ),
        migrations.AlterField(
            model_name="redirectmanual",
            name="slug",
            field=models.CharField(
                max_length=350, primary_key=True, serialize=False, verbose_name="Slug"
            ),
        ),
    ]
