# Generated by Django 4.2.2 on 2023-12-13 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_remove_redirectmanual_id_alter_redirectmanual_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceedition",
            name="clickmeeting_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ClickMeeting ID"
            ),
        ),
        migrations.AddField(
            model_name="conferenceedition",
            name="youtube_live_embed",
            field=models.TextField(blank=True, verbose_name="YouTube Livestream Embed"),
        ),
        migrations.CreateModel(
            name="ConferenceFreeParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64, verbose_name="Imię")),
                ("last_name", models.CharField(max_length=64, verbose_name="Nazwisko")),
                (
                    "voivodeship",
                    models.CharField(
                        choices=[
                            ("DOLNOŚLĄSKIE", "Dolnośląskie"),
                            ("KUJAWSKO-POMORSKIE", "Kujawsko-pomorskie"),
                            ("LUBELSKIE", "Lubelskie"),
                            ("LUBUSKIE", "Lubuskie"),
                            ("ŁÓDZKIE", "Łódzkie"),
                            ("MAŁOPOLSKIE", "Małopolskie"),
                            ("MAZOWIECKIE", "Mazowieckie"),
                            ("OPOLSKIE", "Opolskie"),
                            ("PODKARPACKIE", "Podkarpackie"),
                            ("PODLASKIE", "Podlaskie"),
                            ("POMORSKIE", "Pomorskie"),
                            ("ŚLĄSKIE", "Śląskie"),
                            ("ŚWIĘTOKRZYSKIE", "Świętokrzyskie"),
                            ("WARMIŃSKO-MAZURSKIE", "Warmińsko-mazurskie"),
                            ("WIELKOPOLSKIE", "Wielkopolskie"),
                            ("ZACHODNIOPOMORSKIE", "Zachodniopomorskie"),
                        ],
                        max_length=32,
                        verbose_name="Województwo",
                    ),
                ),
                ("phone", models.CharField(max_length=32, verbose_name="Telefon")),
                (
                    "email",
                    models.EmailField(max_length=32, verbose_name="Adres e-mail"),
                ),
                (
                    "know_from",
                    models.CharField(
                        choices=[("YES", "TAK"), ("NO", "NIE")],
                        max_length=10,
                        verbose_name="Czy korzystasz ze szkoleń zamkniętych w swojej firmie lub jednostce?",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.conferenceedition",
                        verbose_name="Edycja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konferencja (darmowy uczestnik)",
                "verbose_name_plural": "Konferencje (darmowy uczestnik)",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
