# Generated by Django 4.2.2 on 2023-12-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_conferenceedition_clickmeeting_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferencefreeparticipant",
            name="using_closed_webinars",
            field=models.CharField(
                choices=[("YES", "TAK"), ("NO", "NIE")],
                default="NO",
                max_length=10,
                verbose_name="Czy korzystasz ze szkoleń zamkniętych w swojej firmie lub jednostce?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conferencefreeparticipant",
            name="know_from",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Wiadomość e-mail"),
                    ("FACEBOOK", "Facebook"),
                    ("PHONE", "Telefonicznie"),
                    ("INTERNET", "W internecie"),
                    ("FRIEND", "Od znajomego"),
                    ("COWORKER", "Od współpracownika"),
                    ("PUSH", "Powiadomienie na komórce"),
                ],
                max_length=32,
                verbose_name="Skąd dowiedziałeś się o szkoleniu?",
            ),
        ),
    ]
