# Generated by Django 4.2.2 on 2023-12-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_conferencefreeparticipant_using_closed_webinars_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="program_short",
            field=models.TextField(
                blank=True, verbose_name="Program szkolenia (krótki)"
            ),
        ),
        migrations.AlterField(
            model_name="leadmodel",
            name="last_activity_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ostatnia jakakolwiek aktywność"
            ),
        ),
        migrations.AlterField(
            model_name="leadmodel",
            name="last_email_clicked",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Ostatnio kliknięto w wiadomość e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="leadmodel",
            name="last_email_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ostatnio wysłana wiadomość e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="leadmodel",
            name="last_email_opened",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ostatnio otwarto wiadomość e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="leadmodel",
            name="last_purchase_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Ostatnio dokonano zakupu na stronie",
            ),
        ),
        migrations.AlterField(
            model_name="leadmodel",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("NOT_SPECIFIED", "Ogólnie zainteresowany"),
                    ("WEBINAR_PARTICIPANT", "Zgłoszenie - uczestnik webinaru"),
                    ("WEBINAR_CONTACT", "Zgłoszenie -  kontakt ogólny"),
                    ("NEWSLETTER_FOOTER", "Stopka - Zapis do newslettera"),
                    ("CONFERENCE_FREE", "Konferencja - uczestnik darmowy"),
                    ("CONFERENCE_PAID", "Konferencja - uczestnik płatny"),
                    ("EMAIL_MESSAGE_SIGNUP", "E-mail - poprosił od zapis przez e-mail"),
                    ("ARCHIVED_WEBINAR", "Zarchiwizowany webinar"),
                ],
                default="NOT_SPECIFIED",
                max_length=32,
                verbose_name="Źródło lead'a",
            ),
        ),
    ]
