# Generated by Django 4.2.2 on 2023-12-30 13:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_delete_blacklistaggressor_delete_blacklistpleading"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingReplyMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_id",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Message ID",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        max_length=254, verbose_name="Adres E-mail (From)"
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(max_length=254, verbose_name="Adres E-mail (To)"),
                ),
                ("is_aggressor", models.BooleanField(default=False)),
                ("is_vacation", models.BooleanField(default=False)),
                ("is_email_change", models.BooleanField(default=False)),
                (
                    "subject",
                    models.CharField(max_length=256, verbose_name="Tytuł wiadomości"),
                ),
                (
                    "message_content",
                    models.TextField(blank=True, verbose_name="Treść wiadomości"),
                ),
                (
                    "trigger_content",
                    models.TextField(
                        blank=True, verbose_name="Co spowodowało wykrycie?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiadomość e-mail",
                "verbose_name_plural": "Wiadomości e-mail",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="blacklistedemail",
            name="message_content",
            field=models.TextField(blank=True, verbose_name="Treść wiadomości e-mail"),
        ),
        migrations.AddField(
            model_name="blacklistedemail",
            name="reason",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Zablokowano ręcznie"),
                    ("AGGRESSOR", "Agresor"),
                    ("PLEADING", "Grzeczna prośba"),
                ],
                default="MANUAL",
                max_length=32,
                verbose_name="Powód blokowania",
            ),
        ),
    ]
