# Generated by Django 4.2.2 on 2024-01-04 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_conferencecycle_facebook_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lecturer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="webinarcategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webinarcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
