# Generated by Django 4.2.2 on 2024-01-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_lecturer_created_at_lecturer_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceedition",
            name="categories",
            field=models.ManyToManyField(
                to="core.webinarcategory", verbose_name="Kategorie"
            ),
        ),
    ]
