# Generated by Django 4.2.2 on 2024-01-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_conferencefreeparticipant_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceedition",
            name="title",
            field=models.CharField(
                blank=True, max_length=230, verbose_name="Tytuł edycji"
            ),
        ),
    ]
