# Generated by Django 4.2.2 on 2024-01-15 09:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0095_conferenceedition_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomHtmlSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Ścieżka URL",
                        max_length=230,
                        unique=True,
                        verbose_name="Skrót URL",
                    ),
                ),
                ("html", models.TextField(verbose_name="HTML")),
            ],
            options={
                "verbose_name": "Strona HTML",
                "verbose_name_plural": "Strony HTML",
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
