# Generated by Django 4.2.2 on 2024-01-18 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_customhtmlsite_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceedition",
            name="redirect_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
