# Generated by Django 4.2.2 on 2024-01-18 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0098_conferenceedition_redirect_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conferenceedition",
            old_name="youtube_live_embed",
            new_name="youtube_live_url",
        ),
    ]
