# Generated by Django 4.2.2 on 2024-03-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_rename_youtube_live_embed_conferenceedition_youtube_live_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='show_lecturer',
            field=models.BooleanField(default=True, verbose_name='Pokaż wykładowce na stronie szkolenia'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Ukryj termin szkolenia na stronie szkolenia'),
        ),
    ]
