# Generated by Django 4.2.2 on 2024-03-04 08:33

import core.models.mailing.mailing_campaign_model
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_webinar_show_lecturer_alter_webinar_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='resignation_list',
            field=models.CharField(default='default', max_length=32, verbose_name='Lista rezygnacji'),
        ),
        migrations.AlterField(
            model_name='mailingcampaign',
            name='allowed_to_send_after',
            field=models.TimeField(default=core.models.mailing.mailing_campaign_model.default_allowed_to_send_after, verbose_name='Wysyłaj po godzinie'),
        ),
        migrations.AlterField(
            model_name='mailingcampaign',
            name='allowed_to_send_before',
            field=models.TimeField(default=core.models.mailing.mailing_campaign_model.default_allowed_to_send_before, verbose_name='Wysyłaj do godziny'),
        ),
        migrations.AlterField(
            model_name='mailingcampaign',
            name='send_after',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Wysyłaj od dnia i godziny'),
        ),
    ]
