# Generated by Django 4.2.2 on 2024-03-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_mailingcampaign_resignation_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplication',
            name='step_buyer_finished',
            field=models.BooleanField(default=False, help_text='Czy zgłaszający wysłał formularz z nabywcą?', verbose_name='Krok Nabywca zrealizowany'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_invoice_finished',
            field=models.BooleanField(default=False, help_text='Czy zgłaszający wysłał formularz z fakturą?', verbose_name='Krok Faktura zrealizowany'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_participants_finished',
            field=models.BooleanField(default=False, help_text='Czy zgłaszający wysłał formularz z uczestnikami?', verbose_name='Krok Uczestnicy zrealizowany'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_recipient_finished',
            field=models.BooleanField(default=False, help_text='Czy zgłaszający wysłał formularz z odbiorcą?', verbose_name='Krok Odbiorca zrealizowany'),
        ),
    ]
