# Generated by Django 4.2.2 on 2024-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_webinarapplication_step_buyer_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_buyer_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='buyer_end'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_invoice_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invoice_end'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_invoice_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invoice_start'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_participants_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='participants_end'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_participants_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='participants_start'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_recipient_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recipient_end'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_recipient_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recipient_start'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_summary_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='summary_end'),
        ),
        migrations.AddField(
            model_name='webinarapplication',
            name='step_dt_summary_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='summary_start'),
        ),
    ]
