# Generated by Django 4.2.2 on 2024-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_webinarapplication_step_dt_buyer_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplication',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Kod śledzący'),
        ),
    ]
