# Generated by Django 4.2.2 on 2024-05-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_webinarapplication_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceedition',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='conferenceedition',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='conferenceedition',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='conferenceedition',
            name='html',
        ),
        migrations.RemoveField(
            model_name='conferenceedition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conferenceedition',
            name='title',
        ),
        migrations.AddField(
            model_name='conferencecycle',
            name='visible_on_page',
            field=models.BooleanField(default=True, verbose_name='Widoczne na stronie'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='is_connected_to_conference',
            field=models.BooleanField(default=False, help_text='Czy ten webinar jest połączony z konferencją?', verbose_name='Połączony z konferencją'),
        ),
        migrations.AlterField(
            model_name='conferenceedition',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conferencecycle', verbose_name='Konferencja (cykl)'),
        ),
        migrations.AlterField(
            model_name='conferenceedition',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinar', verbose_name='Webinar (płatny dostęp)'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='duration',
            field=models.CharField(choices=[('30', '30 minut'), ('45', '45 minut'), ('60', '1 godzina'), ('90', '1,5 godziny'), ('120', '2 godziny'), ('150', '2,5 godziny'), ('180', '3 godziny'), ('210', '3,5 godziny'), ('240', '4 godziny'), ('270', '4,5 godziny'), ('300', '5 godzin'), ('330', '5,5 godziny'), ('360', '6 godzin'), ('390', '6,5 godziny'), ('420', '7 godzin'), ('450', '7,5 godziny'), ('480', '8 godzin'), ('510', '8,5 godziny'), ('540', '9 godzin')], default='240', max_length=16, verbose_name='Czas trwania'),
        ),
        migrations.DeleteModel(
            name='ConferenceSchedule',
        ),
    ]
