# Generated by Django 4.2.2 on 2024-05-23 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_remove_conferenceedition_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceedition',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.conferencecycle', verbose_name='Konferencja (cykl)'),
        ),
        migrations.AlterField(
            model_name='conferenceedition',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.webinar', verbose_name='Webinar'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Ukryj termin szkolenia na stronie'),
        ),
    ]
