# Generated by Django 4.2.2 on 2024-05-24 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_conferencefreeparticipant_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceedition',
            name='youtube_live_url',
        ),
        migrations.AddField(
            model_name='conferenceedition',
            name='stream_transmission_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Klucz strumienia'),
        ),
        migrations.AddField(
            model_name='conferenceedition',
            name='stream_type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube')], default='YOUTUBE', max_length=16, verbose_name='Gdzie stream?'),
        ),
        migrations.AddField(
            model_name='conferenceedition',
            name='stream_url_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres URL serwera'),
        ),
        migrations.AddField(
            model_name='conferencefreeparticipant',
            name='watch_token',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Token wypisu'),
        ),
        migrations.AlterField(
            model_name='conferenceedition',
            name='clickmeeting_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ClickMeeting ID'),
        ),
    ]
