# Generated by Django 4.2.2 on 2024-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_conferenceedition_clickmeeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceedition',
            name='stream_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres URL strumienia'),
        ),
    ]
