# Generated by Django 4.2.2 on 2024-05-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_conferenceedition_stream_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferenceedition',
            old_name='stream_url_address',
            new_name='stream_server_url',
        ),
        migrations.RemoveField(
            model_name='conferenceedition',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='conferenceedition',
            name='stream_url_page',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres URL strony'),
        ),
    ]
