# Generated by Django 4.2.2 on 2024-05-25 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_rename_stream_url_address_conferenceedition_stream_server_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceedition',
            name='clickmeeting_pasted',
            field=models.BooleanField(default=False, verbose_name='Dane strumienia przeklejone?'),
        ),
        migrations.AlterField(
            model_name='conferencefreeparticipant',
            name='watch_token',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Token panelu oglądania'),
        ),
    ]
