# Generated by Django 4.2.2 on 2024-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_conferenceedition_clickmeeting_pasted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceedition',
            name='clickmeeting_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ClickMeeting ID'),
        ),
        migrations.AlterField(
            model_name='conferenceedition',
            name='clickmeeting_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='ClickMeeting URL'),
        ),
    ]
