# Generated by Django 4.2.2 on 2024-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_conferenceedition_clickmeeting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='any_error_occured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='connection_refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='smtp_server_disconnected',
            field=models.BooleanField(default=False),
        ),
    ]
