# Generated by Django 4.2.2 on 2024-06-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_mailingcampaign_any_error_occured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarparticipantmetadata',
            name='uncertain',
            field=models.BooleanField(default=False, verbose_name='Niepewny?'),
        ),
    ]
