# Generated by Django 4.2.2 on 2024-06-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_webinarparticipantmetadata_uncertain'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarApplicationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Stworzono')),
                ('tracking_code', models.CharField(max_length=64, verbose_name='Kod śledzący')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.webinar', verbose_name='Webinar')),
            ],
        ),
    ]
