# Generated by Django 4.2.2 on 2024-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_user_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='years_experience',
            field=models.CharField(blank=True, help_text='np. `5 lat`', max_length=40, verbose_name='Lata doświadczenia'),
        ),
    ]
