# Generated by Django 4.2.2 on 2024-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_webinarrecordingtoken_starts_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplication',
            name='recording_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Początek dostępu do nagrania'),
        ),
    ]
