# Generated by Django 4.2.2 on 2024-08-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_webinarapplication_recording_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcompany',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploads/company_logos', verbose_name='Logo firmy'),
        ),
    ]
