# Generated by Django 4.2.2 on 2024-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_crmcompany_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcompany',
            name='logo_visible_on_page',
            field=models.BooleanField(default=False, help_text='Czy logo jest widoczne na stronie', verbose_name='Logo widoczne'),
        ),
    ]
