# Generated by Django 4.2.2 on 2024-08-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_crmcompany_logo_visible_on_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcompany',
            name='page_ordering',
            field=models.PositiveIntegerField(default=100, verbose_name='Sortowanie'),
        ),
    ]
