# Generated by Django 4.2.2 on 2024-08-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_crmcompany_page_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceedition',
            name='stream_url_embed',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres Embed'),
        ),
    ]
