# Generated by Django 4.2.2 on 2024-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_conferenceedition_stream_url_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureropinion',
            name='lecturer_reply',
            field=models.TextField(blank=True, verbose_name='Odpowiedź wykładowcy'),
        ),
    ]
