# Generated by Django 4.2.2 on 2024-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_lectureropinion_lecturer_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureropinion',
            name='flagship_opinion',
            field=models.BooleanField(default=False, verbose_name='Widoczna w panelu wykładowcy'),
        ),
    ]
