# Generated by Django 4.2.2 on 2024-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_lectureropinion_flagship_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='resets_counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Ilość resetów'),
        ),
    ]
