# Generated by Django 4.2.2 on 2024-08-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_mailingcampaign_resets_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingcampaign',
            name='stat_procesed',
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='failure_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='smtp_recipients_refused',
            field=models.BooleanField(default=False),
        ),
    ]
