# Generated by Django 4.2.2 on 2024-08-22 16:15

import core.libs.validators.nip_validator
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_remove_mailingcampaign_stat_procesed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Stworzono')),
                ('slug', models.SlugField(help_text='Slug', max_length=150, unique=True, verbose_name='Skrót URL')),
                ('offer_title', models.CharField(max_length=250, verbose_name='Nazwa oferty')),
                ('short_name', models.CharField(max_length=100, verbose_name='Krótka Nazwa')),
                ('description_primary_html', models.TextField(default='[DESCRIPTION_PRIMARY]', verbose_name='DESCRIPTION PRIMARY')),
                ('steps_html', models.TextField(default='[STEPS]', verbose_name='STEPS')),
                ('call_to_action_html', models.TextField(default='[CTA]', verbose_name='CTA HTML')),
                ('button_html', models.TextField(default='[BUTTON]', verbose_name='BUTTON HTML')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.webinarcategory')),
            ],
            options={
                'verbose_name': 'Oferta Usługi',
                'verbose_name_plural': 'Oferty Usług',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOfferLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Stworzono')),
                ('tracking_code', models.CharField(blank=True, max_length=32, verbose_name='Kod śledzący')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('service_offer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.serviceoffer')),
            ],
            options={
                'verbose_name': 'Oferta Usługi - Leady',
                'verbose_name_plural': 'Oferty Usług - Leady',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOfferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Stworzono')),
                ('status', models.CharField(choices=[('SENT', 'Wysłano zgłoszenie'), ('OFFER', 'Przygotowano ofertę'), ('ACCEPTED', 'Klient zaakceptował ofertę'), ('REJECTED', 'Klient odrzucił ofertę'), ('PAID', 'Zapłacono za usługę'), ('UNPAID', 'Nie zapłacono za usługę')], default='SENT', max_length=32)),
                ('nip', models.CharField(max_length=32, validators=[core.libs.validators.nip_validator.validate_nip_modelfield], verbose_name='NIP')),
                ('name', models.CharField(max_length=250, verbose_name='Nazwa')),
                ('address', models.CharField(max_length=150, verbose_name='Adres')),
                ('postal_code', models.CharField(max_length=16, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=150, verbose_name='Miejscowość')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email kontaktowy')),
                ('email_confirmation', models.EmailField(blank=True, max_length=254, verbose_name='Email potwierdzenie')),
                ('phone', models.CharField(max_length=50, verbose_name='Numer telefonu')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/offer_contact', verbose_name='Plik')),
                ('additional_info', models.TextField(blank=True, max_length=250, verbose_name='Uwagi')),
                ('accepted_rodo', models.BooleanField(verbose_name='Zaakceptowano RODO')),
                ('accepted_terms', models.BooleanField(verbose_name='Zaakceptowano Regulamin')),
                ('tracking_code', models.CharField(blank=True, max_length=32, verbose_name='Kod śledzący')),
                ('sent_at', models.DateTimeField(null=True)),
                ('sent_ip_address', models.CharField(blank=True, max_length=64)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('accepted_ip_address', models.CharField(blank=True, max_length=64)),
                ('service_offer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.serviceoffer')),
            ],
            options={
                'verbose_name': 'Oferta Usługi - Zgłoszenie',
                'verbose_name_plural': 'Oferty Usług - Zgłoszenia',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
