# Generated by Django 4.2.2 on 2024-08-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_serviceoffer_serviceofferlead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='file_text',
            field=models.TextField(default='[FILE_TEXT]', verbose_name='FILE_TEXT'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='place_text',
            field=models.TextField(default='[PLACE_TEXT]', verbose_name='PLACE_TEXT'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='thanks_html',
            field=models.TextField(default='[THANKS_HTML]', verbose_name='THANKS_HTML'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='thanks_title_text',
            field=models.TextField(default='[THANKS_TITLE_TEXT]', verbose_name='THANKS_TITLE_TEXT'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='button_html',
            field=models.TextField(default='[BUTTON_HTML]', verbose_name='BUTTON_HTML'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='call_to_action_html',
            field=models.TextField(default='[CALL_TO_ACTION_HTML]', verbose_name='CTA_HTML'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='steps_html',
            field=models.TextField(default='[STEPS_HTML]', verbose_name='STEPS_HTML'),
        ),
    ]
