# Generated by Django 4.2.2 on 2024-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_serviceoffer_mailing_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='finished_coop',
            field=models.BooleanField(default=False, help_text='Wykładowca nie chce mieć z nami nic wspólnego', verbose_name='Zakończono współpracę'),
        ),
    ]
