# Generated by Django 4.2.2 on 2024-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_lecturer_finished_coop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='base_priority',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='random_priority',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='random_priority_max',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='random_priority_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
