# Generated by Django 4.2.2 on 2024-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_mailingcampaign_base_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsender',
            name='exclude_from_processing',
            field=models.BooleanField(default=False, verbose_name='Exclude from processing'),
        ),
    ]
