# Generated by Django 4.2.2 on 2024-09-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_smtpsender_exclude_from_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='mod_value',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
