# Generated by Django 4.2.2 on 2024-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_mailingcampaign_mod_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='pause_on_too_many_failures',
            field=models.BooleanField(default=True),
        ),
    ]
