# Generated by Django 4.2.2 on 2024-09-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_survey_surveyanswer_surveyvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='total_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
