# Generated by Django 4.2.2 on 2024-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_mailingcampaign_total_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplication',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID kampanii mailingowej'),
        ),
        migrations.AddField(
            model_name='webinarapplicationtracking',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID kampanii mailingowej'),
        ),
    ]
