# Generated by Django 4.2.2 on 2024-10-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_webinarapplication_campaign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsender',
            name='sender_alias',
            field=models.CharField(blank=True, max_length=32, verbose_name='Alias konta wysyłkowego'),
        ),
    ]
