# Generated by Django 4.2.2 on 2024-10-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_smtpsender_sender_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='sent_start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
