# Generated by Django 4.2.2 on 2024-10-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_mailingcampaign_sent_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcampaign',
            name='sent_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
