# Generated by Django 4.2.2 on 2024-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_mailingcampaign_target_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='favourite',
            field=models.BooleanField(default=False, verbose_name='Ulubiona kampania'),
        ),
    ]
