# Generated by Django 4.2.2 on 2024-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_mailingcampaign_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceofferapplication',
            name='uncertain',
            field=models.BooleanField(default=False, verbose_name='Niepewny?'),
        ),
    ]
