# Generated by Django 4.2.2 on 2024-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_alter_serviceofferapplication_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceofferapplication',
            name='status',
            field=models.CharField(choices=[('SENT', 'Wysłano zgłoszenie'), ('OFFER', 'Przygotowano ofertę'), ('ACCEPTED', 'Klient zaakceptował ofertę'), ('REJECTED', 'Klient odrzucił ofertę'), ('PAID', 'Zapłacono za usługę'), ('UNPAID', 'Nie zapłacono za usługę'), ('TRASH', 'Śmieciowe zgłoszenie')], default='SENT', max_length=32),
        ),
    ]
