# Generated by Django 4.2.2 on 2024-10-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_alter_serviceofferapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='additional_info_text',
            field=models.TextField(default='Dodatkowe uwagi (opcjonalnie)', verbose_name='ADDITIONAL_INFO_TEXT'),
        ),
        migrations.AddField(
            model_name='serviceofferapplication',
            name='accepted_conditions',
            field=models.BooleanField(default=False, verbose_name='Zaakceptowali warunki?'),
        ),
        migrations.AddField(
            model_name='serviceofferapplication',
            name='no_answer',
            field=models.BooleanField(default=False, verbose_name='Brak odpowiedzi?'),
        ),
        migrations.AddField(
            model_name='serviceofferapplication',
            name='resigned',
            field=models.BooleanField(default=False, verbose_name='Zrezygnowali?'),
        ),
    ]
