# Generated by Django 4.2.2 on 2024-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_serviceoffer_additional_info_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='add_placeholder',
            field=models.CharField(default='[add_placeholder]', max_length=128, verbose_name='Placeholder add'),
        ),
        migrations.AddField(
            model_name='survey',
            name='search_placeholder',
            field=models.CharField(default='[search_placeholder]', max_length=128, verbose_name='Placeholder search'),
        ),
    ]
