# Generated by Django 4.2.2 on 2024-11-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_surveyanswer_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='avatar_placeholders_enabled',
            field=models.BooleanField(default=False, verbose_name='Wyświetlaj domyślny avatar jeśli wykładowca nie jest ustawiony w odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Nie będzie można wyszukać terminu, ale będzie można wejść bezpośrednio', verbose_name='Ukryj termin szkolenia na stronie'),
        ),
    ]
