# Generated by Django 4.2.2 on 2024-11-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_survey_avatar_placeholders_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='ask_about_opinion_enabled',
            field=models.BooleanField(default=False, verbose_name='Pytaj o opinie po wysłaniu głosu'),
        ),
    ]
