# Generated by Django 4.2.2 on 2024-11-09 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_survey_ask_about_opinion_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter_id', models.CharField(max_length=100, verbose_name='ID głosującego')),
                ('answer_title', models.CharField(max_length=150, verbose_name='Nazwa odpowiedzi')),
                ('opinion_text', models.TextField(verbose_name='Treść opinii')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.survey', verbose_name='Ankieta')),
            ],
            options={
                'verbose_name': 'Ankieta (Opinia)',
                'verbose_name_plural': 'Ankiety (Opinie)',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
