# Generated by Django 4.2.2 on 2024-11-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_surveyopinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarcategory',
            name='fakturownia_category_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID Kategorii w Fakturowni'),
        ),
    ]
