# Generated by Django 4.2.2 on 2024-11-11 15:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_webinarcategory_fakturownia_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturowniaCategory',
            fields=[
                ('fakturownia_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID w Fakturowni')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Fakturownia - Kategoria',
                'verbose_name_plural': 'Fakturownia - Kategorie',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
