# Generated by Django 4.2.2 on 2024-11-15 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_fakturowniacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='fakturownia_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fakturowniacategory', verbose_name='Kategoria Fakturownia'),
        ),
    ]
