# Generated by Django 4.2.2 on 2024-11-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_webinar_fakturownia_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='sending_batch_size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='sleep_between_batches',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
