# Generated by Django 4.2.2 on 2024-11-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_mailingcampaign_sending_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsender',
            name='bucket_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
