# Generated by Django 4.2.2 on 2024-11-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_smtpsender_bucket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='inherit_bucket_id_from_sender',
            field=models.BooleanField(default=True),
        ),
    ]
