# Generated by Django 4.2.2 on 2024-11-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_mailingcampaign_inherit_bucket_id_from_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='sleep_every_send',
            field=models.FloatField(default=0.1),
        ),
    ]
