# Generated by Django 4.2.2 on 2024-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_mailingcampaign_sleep_every_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceedition',
            name='dashboard_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres URL dashboard'),
        ),
    ]
