# Generated by Django 4.2.2 on 2024-12-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_conferenceedition_dashboard_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='mailing_short_html',
            field=models.TextField(default='[MAILING_SHORT_HTML]', verbose_name='MAILING_SHORT_HTML'),
        ),
    ]
