# Generated by Django 4.2.2 on 2024-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_serviceoffer_mailing_short_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceedition',
            name='advert_facebook_html',
            field=models.TextField(blank=True, verbose_name='Advert FB HTML'),
        ),
        migrations.AddField(
            model_name='conferenceedition',
            name='advert_facebook_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Advert FB URL'),
        ),
    ]
