# Generated by Django 4.2.2 on 2024-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_conferenceedition_advert_webinar_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='program_word_text',
            field=models.TextField(blank=True, verbose_name='Program (Word Text)'),
        ),
    ]
