# Generated by Django 4.2.2 on 2024-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_webinar_program_word_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='remaining_places',
            field=models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Pozostało miejsc'),
        ),
    ]
