# Generated by Django 4.2.2 on 2024-12-26 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_alter_webinar_remaining_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='anonymize_lecturer',
            field=models.BooleanField(default=False, help_text='Wykładowca będzie zanonimizowany', verbose_name='Anonimizuj wykładowcę'),
        ),
        migrations.CreateModel(
            name='MailingScheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('INIT', 'Do zaplanowania'), ('SCHEDULED', 'Zaplanowano'), ('CANCELED', 'Odwołano zaplanowanie')], default='INIT', max_length=32)),
                ('schedule_after', models.DateTimeField(help_text='Po jakiej dacie ma być stworzona kampania', verbose_name='Zaplanuj po dacie')),
                ('target_date', models.DateField(help_text='Kiedy ma się wysyłać kampania', verbose_name='Mailing na dzień')),
                ('url', models.CharField(max_length=512, verbose_name='URL szablonu')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł kampanii')),
                ('subjects', models.TextField(verbose_name='Tytuły wiadomości e-mail')),
                ('alias', models.CharField(max_length=64, verbose_name='Alias')),
                ('tags', models.TextField(blank=True, help_text='Z jakich tagów mają zostać wrzucone adresy e-mail', verbose_name='Tagi')),
                ('campaign_id', models.ForeignKey(blank=True, help_text='Jaka kampania została stworzona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mailingcampaign', verbose_name='Stworzona kampania')),
                ('webinar', models.ForeignKey(blank=True, help_text='Jakiego szkolenia dotyczy mailing?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinar', verbose_name='Szkolenie')),
            ],
            options={
                'verbose_name': 'Mailing Kampania (Zaplanowana)',
                'verbose_name_plural': 'Mailing Kampanie (Zaplanowane)',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
