# Generated by Django 4.2.2 on 2024-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_webinar_anonymize_lecturer_mailingscheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='anonymize',
            field=models.BooleanField(default=False, help_text='Wykładowca będzie zanonimizowany', verbose_name='Anonimizuj wykładowcę'),
        ),
        migrations.AddField(
            model_name='webinarmetadata',
            name='fetched_from',
            field=models.CharField(blank=True, max_length=32, verbose_name='fetched_from'),
        ),
        migrations.AddField(
            model_name='webinarmetadata',
            name='fetched_from_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='fetched_from_url'),
        ),
        migrations.AddField(
            model_name='webinarmetadata',
            name='fetched_too_long_title',
            field=models.BooleanField(default=False, verbose_name='fetched_too_long_title'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Wersja robocza'), ('INIT', 'Planowany termin'), ('CONFIRMED', 'Termin potwierdzony'), ('CANCELED', 'Termin odwołany'), ('DONE', 'Termin zrealizowany')], default='INIT', max_length=32),
        ),
    ]
