# Generated by Django 4.2.2 on 2024-12-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_lecturer_anonymize_webinarmetadata_fetched_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingscheduled',
            name='resignation_list',
            field=models.CharField(default='default', max_length=32, verbose_name='Lista rezygnacji'),
        ),
        migrations.AddField(
            model_name='mailingscheduled',
            name='smtp_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.smtpsender', verbose_name='Konto wysyłkowe'),
        ),
        migrations.AddField(
            model_name='mailingscheduled',
            name='target_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='target_code'),
        ),
        migrations.AddField(
            model_name='mailingscheduled',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mailingtemplate'),
        ),
    ]
