# Generated by Django 4.2.2 on 2024-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_mailingscheduled_logi_mailingscheduled_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarmetadata',
            name='omega_indexer_queued',
            field=models.BooleanField(default=False, verbose_name='omega_indexer_queued'),
        ),
    ]
