# Generated by Django 4.2.2 on 2024-12-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_webinarmetadata_omega_indexer_queued'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWebinar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Pokaż `Pewny termin` przy szkoleniu na stronie', verbose_name='Pewny termin')),
                ('is_fake', models.BooleanField(default=False, verbose_name="Fake'owy termin")),
                ('show_lecturer', models.BooleanField(default=True, verbose_name='Pokaż wykładowce na stronie szkolenia')),
                ('anonymize_lecturer', models.BooleanField(default=False, help_text='Wykładowca będzie zanonimizowany', verbose_name='Anonimizuj wykładowcę')),
                ('is_hidden', models.BooleanField(default=False, help_text='Nie będzie można wyszukać terminu, ale będzie można wejść bezpośrednio', verbose_name='Ukryj termin szkolenia na stronie')),
                ('is_connected_to_conference', models.BooleanField(default=False, help_text='Czy ten webinar jest połączony z konferencją?', verbose_name='Połączony z konferencją')),
                ('recording_allowed', models.BooleanField(default=False, help_text='Wykładowca zgadza się na nagranie z tego szkolenia', verbose_name='Nagrania dostępne')),
                ('remaining_places', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='Pozostało miejsc')),
                ('status', models.CharField(choices=[('DRAFT', 'Wersja robocza'), ('INIT', 'Planowany termin'), ('CONFIRMED', 'Termin potwierdzony'), ('CANCELED', 'Termin odwołany'), ('DONE', 'Termin zrealizowany')], default='INIT', max_length=32)),
                ('title_original', models.TextField(help_text='Tytuł szkolenia jaki został dostarczony przez wykładowce', verbose_name='Pełny tytuł szkolenia')),
                ('title', models.TextField(help_text='Tytuł szkolenia zmodyfikowany, aby mieścił się w ogrniczonej ilości znaków', max_length=220, verbose_name='Tytuł szkolenia')),
                ('slug', models.SlugField(blank=True, help_text='Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)', max_length=230, verbose_name='Skrót URL')),
                ('description', models.TextField(blank=True, help_text='Dodatkowy opis webinaru', max_length=200, verbose_name='Dodatkowy opis')),
                ('date', models.DateTimeField(verbose_name='Data i Godzina')),
                ('duration', models.CharField(choices=[('30', '30 minut'), ('45', '45 minut'), ('60', '1 godzina'), ('90', '1,5 godziny'), ('120', '2 godziny'), ('150', '2,5 godziny'), ('180', '3 godziny'), ('210', '3,5 godziny'), ('240', '4 godziny'), ('270', '4,5 godziny'), ('300', '5 godzin'), ('330', '5,5 godziny'), ('360', '6 godzin'), ('390', '6,5 godziny'), ('420', '7 godzin'), ('450', '7,5 godziny'), ('480', '8 godzin'), ('510', '8,5 godziny'), ('540', '9 godzin')], default='240', max_length=16, verbose_name='Czas trwania')),
                ('price_netto', models.PositiveSmallIntegerField(verbose_name='Cena NETTO')),
                ('discount_netto', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Cena NETTO (Promocyjna)')),
                ('discount_until', models.DateTimeField(blank=True, null=True, verbose_name='Promocja do')),
                ('program', models.TextField(default='[Program Szkolenia]', verbose_name='Program szkolenia')),
                ('program_markdown', models.TextField(blank=True, verbose_name='Program szkolenia (markdown)')),
                ('program_pretty', models.TextField(blank=True, verbose_name='Program szkolenia (enchanted)')),
                ('program_short', models.TextField(blank=True, verbose_name='Program szkolenia (krótki)')),
                ('program_word_text', models.TextField(blank=True, verbose_name='Program (Word Text)')),
                ('external_name', models.CharField(blank=True, max_length=64, verbose_name='Zewnętrzny dostawca - Nazwa')),
                ('external_url', models.URLField(blank=True, verbose_name='Zewnętrzny dostawca - URL')),
                ('external_description', models.TextField(blank=True, verbose_name='Zewnętrzny dostawca - Opis')),
                ('grouping_token', models.CharField(blank=True, help_text='Ciąg znaków grupujący razem terminy', max_length=32, verbose_name='Token grupujący')),
                ('facebook_post_image', models.TextField(blank=True, help_text='wymiary: 1200px na 630px', max_length=100, verbose_name='Facebook Post Image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fakturownia_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.fakturowniacategory', verbose_name='Kategoria Fakturownia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.lecturer', verbose_name='Wykładowca')),
            ],
            options={
                'verbose_name': 'historical Webinar',
                'verbose_name_plural': 'historical Webinary',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
