# Generated by Django 4.2.2 on 2025-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_historicalwebinar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='is_main_campaign',
            field=models.BooleanField(default=False, help_text='Oznacza, że ta kampania jest kampanią główną dla szkolenia', verbose_name='Główna kampania'),
        ),
        migrations.AlterField(
            model_name='mailingscheduled',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Kiedy automat stworzył kampanie?', null=True, verbose_name='Stworzony automatycznie'),
        ),
    ]
