# Generated by Django 4.2.2 on 2025-01-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_mailingcampaign_is_main_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='biography_anonymous',
            field=models.TextField(blank=True, verbose_name='Biografia (anonim)'),
        ),
    ]
