# Generated by Django 4.2.2 on 2025-01-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_lecturer_biography_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarmetadata',
            name='mailing_dobijanie_enabled',
            field=models.BooleanField(default=False, verbose_name='mailing_dobijanie_enabled'),
        ),
    ]
