# Generated by Django 4.2.2 on 2025-01-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_webinarmetadata_mailing_dobijanie_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='is_dobijanie',
            field=models.BooleanField(default=False, verbose_name='is_dobijanie'),
        ),
    ]
