# Generated by Django 4.2.2 on 2025-01-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_lecturer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebinar',
            name='seo_manual_redirect',
            field=models.CharField(blank=True, help_text='SEO Manual Redirect', max_length=512, verbose_name='SEO Manual Redirect'),
        ),
        migrations.AddField(
            model_name='historicalwebinar',
            name='seo_webinar_redirect',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.webinar', verbose_name='SEO Webinar Redirect'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='seo_manual_redirect',
            field=models.CharField(blank=True, help_text='SEO Manual Redirect', max_length=512, verbose_name='SEO Manual Redirect'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='seo_webinar_redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.webinar', verbose_name='SEO Webinar Redirect'),
        ),
    ]
