# Generated by Django 4.2.2 on 2025-01-17 17:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_historicalwebinar_seo_manual_redirect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarAggregate',
            fields=[
                ('status', models.CharField(choices=[('DRAFT', 'Wersja robocza'), ('PUBLISHED', 'Opublikowany')], default='DRAFT', max_length=32)),
                ('slug', models.SlugField(help_text='Unikalny skrót pojawiający się w adresie URL (Ważne dla SEO)', max_length=230, unique=True, verbose_name='Skrót URL')),
                ('grouping_token', models.CharField(help_text='Ciąg znaków grupujący razem terminy', max_length=32, primary_key=True, serialize=False, verbose_name='Token grupujący')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
