# Generated by Django 4.2.2 on 2025-02-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_webinaraggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebinar',
            name='program_assets',
            field=models.TextField(blank=True, verbose_name='Materiały szkoleniowe'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='program_assets',
            field=models.TextField(blank=True, verbose_name='Materiały szkoleniowe'),
        ),
        migrations.AlterField(
            model_name='webinaraggregate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Wersja robocza'), ('PUBLISHED', 'Opublikowany'), ('REJECTED', 'Odrzucony')], default='DRAFT', max_length=32),
        ),
    ]
