# Generated by Django 4.2.2 on 2025-02-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_historicalwebinar_program_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplicationmetadata',
            name='vat_status',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
