# Generated by Django 4.2.2 on 2025-03-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_webinarapplicationmetadata_vat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarparticipantmetadata',
            name='sms_reminder_consent',
            field=models.BooleanField(default=False, verbose_name='Zgoda na SMS przypominający?'),
        ),
        migrations.AddField(
            model_name='webinarparticipantmetadata',
            name='sms_reminder_send',
            field=models.BooleanField(default=False, verbose_name='Wysłano SMS przypominający?'),
        ),
        migrations.AddField(
            model_name='webinarparticipantmetadata',
            name='sms_reminder_send_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
