# Generated by Django 4.2.2 on 2025-03-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_webinarparticipantmetadata_sms_reminder_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarparticipantmetadata',
            name='sms_reminder_send_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
