# Generated by Django 4.2.2 on 2025-03-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_alter_webinarparticipantmetadata_sms_reminder_send_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='forbid_mailing_alias',
            field=models.BooleanField(default=False, help_text='Wykładowca nie chce być widoczny z imienia i nazwiska w aliasie w mailingu', verbose_name='Nie chce być w Aliasie w mailingu'),
        ),
    ]
