# Generated by Django 4.2.2 on 2025-04-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_lecturer_forbid_mailing_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplication',
            name='fake_application',
            field=models.BooleanField(default=False, help_text='Czy prawdopodobnie fałszywe zgłoszenie?', verbose_name='Fałszywe zgłoszenie'),
        ),
    ]
