# Generated by Django 4.2.2 on 2025-04-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_webinarapplication_fake_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarparticipantmetadata',
            name='sms_reminder_consent',
        ),
        migrations.RemoveField(
            model_name='webinarparticipantmetadata',
            name='sms_reminder_send',
        ),
        migrations.RemoveField(
            model_name='webinarparticipantmetadata',
            name='sms_reminder_send_dt',
        ),
    ]
