# Generated by Django 4.2.2 on 2025-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_remove_webinarparticipantmetadata_sms_reminder_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarparticipant',
            name='sms_reminder_consent',
            field=models.BooleanField(default=False, verbose_name='Zgoda na SMS przypominający?'),
        ),
        migrations.AddField(
            model_name='webinarparticipant',
            name='sms_reminder_send',
            field=models.BooleanField(default=False, verbose_name='Wysłano SMS przypominający?'),
        ),
        migrations.AddField(
            model_name='webinarparticipant',
            name='sms_reminder_send_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
