# Generated by Django 4.2.2 on 2025-04-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_webinarparticipant_sms_reminder_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarparticipant',
            name='sms_error_msg',
            field=models.CharField(blank=True, max_length=100, verbose_name='SMS błąd'),
        ),
    ]
