# Generated by Django 4.2.2 on 2025-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_webinarparticipant_sms_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplication',
            name='fake_application_logs',
            field=models.TextField(blank=True, help_text='Logi detektora fałszywych zgłoszeń', verbose_name='Fałszywe zgłoszenie (logi)'),
        ),
    ]
