# Generated by Django 4.2.2 on 2025-05-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_salerecording_salerecordingapplicationcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebinar',
            name='sale_recording',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.salerecording', verbose_name='Nagranie na sprzedaż'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='sale_recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salerecording', verbose_name='Nagranie na sprzedaż'),
        ),
    ]
