# Generated by Django 4.2.2 on 2025-05-01 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_historicalwebinar_sale_recording_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecordingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INIT', 'Init'), ('ACCESS_SENT', 'Wysłano dostęp do nagrania')], default='', max_length=32)),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('access_from', models.DateField(verbose_name='Dostęp od dnia')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salerecordingapplication', verbose_name='Zamówienie')),
            ],
            options={
                'verbose_name': 'Uczestnik (nagranie na sprzedaż)',
                'verbose_name_plural': 'Uczestnicy (nagranie na sprzedaż)',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
