# Generated by Django 4.2.2 on 2025-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_salerecordingparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecordingparticipant',
            name='access_from',
            field=models.DateField(blank=True, null=True, verbose_name='Dostęp od dnia'),
        ),
    ]
