# Generated by Django 4.2.2 on 2025-05-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_alter_salerecordingparticipant_access_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecordingapplication',
            name='fakturownia_payment_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
