# Generated by Django 4.2.2 on 2025-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_crmnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmnote',
            name='hide_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmnote',
            name='show_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
