# Generated by Django 4.2.2 on 2025-05-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_alter_crmnote_hide_after_alter_crmnote_show_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmnote',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
