# Generated by Django 4.2.2 on 2025-05-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_crmnote_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinaraggregate',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalwebinar',
            name='webinar_aggregate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(Samo się wypełni) Agregat grupujący terminy webinarów', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.webinaraggregate', verbose_name='Agregat'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='webinar_aggregate',
            field=models.ForeignKey(blank=True, help_text='(Samo się wypełni) Agregat grupujący terminy webinarów', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinaraggregate', verbose_name='Agregat'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='absolute_redirect',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinaraggregate', verbose_name='Rodzic'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='webinars',
            field=models.ManyToManyField(blank=True, help_text='[Autouzupełnianie]', to='core.webinar', verbose_name='Terminy'),
        ),
    ]
