# Generated by Django 4.2.2 on 2025-05-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_remove_webinaraggregate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='slug_conflict',
            field=models.BooleanField(default=False, verbose_name='Slug conflict'),
        ),
    ]
