# Generated by Django 4.2.2 on 2025-05-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_webinaraggregate_slug_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.webinarcategory', verbose_name='Kategorie'),
        ),
    ]
