# Generated by Django 4.2.2 on 2025-05-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_webinaraggregate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='title',
            field=models.TextField(blank=True, help_text='Tytuł szkolenia zmodyfikowany, aby mieścił się w ogrniczonej ilości znaków', max_length=220, verbose_name='Tytuł szkolenia'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='title_conflict',
            field=models.BooleanField(default=False, verbose_name='Title conflict'),
        ),
    ]
