# Generated by Django 4.2.2 on 2025-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_webinaraggregate_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='closest_webinar_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='has_active_webinars',
            field=models.BooleanField(default=False, verbose_name='Ma aktywne webinary'),
        ),
    ]
