# Generated by Django 4.2.2 on 2025-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_webinaraggregate_closest_webinar_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedWebinarContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('full_name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Firma')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('tracking_info', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa (szkolenie zamknięte)',
                'verbose_name_plural': 'Wiadomości kontaktowe (szkolenie zamknięte)',
            },
        ),
    ]
