# Generated by Django 4.2.2 on 2025-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_closedwebinarcontactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedwebinarcontactmessage',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Treść wiadomości'),
        ),
    ]
