# Generated by Django 4.2.2 on 2025-05-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0207_alter_closedwebinarcontactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lecturer', verbose_name='Wykładowca'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='program',
            field=models.TextField(blank=True, default='[Agregat Program Szkolenia]', verbose_name='Program szkolenia'),
        ),
    ]
