# Generated by Django 4.2.2 on 2025-05-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_webinaraggregate_lecturer_webinaraggregate_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='lecturer_conflict',
            field=models.BooleanField(default=False, verbose_name='Lecturer conflict'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='program_conflict',
            field=models.BooleanField(default=False, verbose_name='Program conflict'),
        ),
    ]
