# Generated by Django 4.2.2 on 2025-05-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_webinaraggregate_lecturer_conflict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarcategory',
            name='name_homepage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwa kategorii (strona główna)'),
        ),
    ]
