# Generated by Django 4.2.2 on 2025-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_webinarcategory_name_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarcategory',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tytuł kategorii'),
        ),
    ]
