# Generated by Django 4.2.2 on 2025-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_webinarcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarcategory',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Krótki opis'),
        ),
    ]
