# Generated by Django 4.2.2 on 2025-05-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_alter_webinarcategory_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Krótki opis'),
        ),
    ]
