# Generated by Django 4.2.2 on 2025-05-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_webinaraggregate_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Ukryty'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='sale_recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salerecording', verbose_name='Nagranie na sprzedaż'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='seo_canonical_url',
            field=models.URLField(blank=True, verbose_name='SEO Canonical URL'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='seo_meta_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='SEO Meta Description'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='seo_meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO Meta Title'),
        ),
        migrations.AlterField(
            model_name='webinaraggregate',
            name='title',
            field=models.TextField(blank=True, help_text='Max. 220 znaków', max_length=220, verbose_name='Tytuł szkolenia'),
        ),
    ]
