# Generated by Django 4.2.2 on 2025-05-30 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_webinaraggregate_hidden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webinaraggregate',
            options={'verbose_name': 'Agregat', 'verbose_name_plural': 'Agregaty'},
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
