# Generated by Django 4.2.2 on 2025-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_alter_webinaraggregate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='program_assets',
            field=models.TextField(blank=True, verbose_name='Materiały szkoleniowe'),
        ),
        migrations.AddField(
            model_name='webinaraggregate',
            name='program_assets_conflict',
            field=models.BooleanField(default=False, verbose_name='Materiały szkoleniowe conflict'),
        ),
    ]
