# Generated by Django 4.2.2 on 2025-06-14 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_webinaraggregate_program_assets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpyObject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('WEBINAR_SEE_MORE', 'Kliknięcie: Webinar przycisk zobacz więcej'), ('VISITED_CLOSED_WEBINAR_PAGE', 'Wejście: Strona szkolenie zamknięte')], max_length=64, verbose_name='Źródło')),
                ('param_a', models.CharField(blank=True, max_length=64)),
                ('param_b', models.CharField(blank=True, max_length=64)),
                ('param_c', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('tracking_code', models.CharField(blank=True, max_length=32, verbose_name='Kod śledzący')),
                ('campaign_id', models.CharField(blank=True, max_length=32, verbose_name='ID kampanii mailingowej')),
                ('fingerprint', models.CharField(blank=True, max_length=128)),
                ('user_agent', models.CharField(blank=True, max_length=128)),
                ('logged_in', models.BooleanField(default=False, verbose_name='Zalogowany?')),
                ('user_id', models.CharField(blank=True, max_length=16)),
                ('google_recaptcha_v3', models.FloatField(default=-1.0, verbose_name='Google reCAPTCHA v3')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Adres E-mail')),
                ('aggregate_current_title', models.CharField(blank=True, max_length=256)),
                ('sent_notification', models.BooleanField(default=False, verbose_name='Wysłano e-mail?')),
                ('sent_notification_at', models.DateTimeField(blank=True, null=True, verbose_name='Kiedy wysłano e-mail')),
                ('aggregate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.webinaraggregate', verbose_name='Agregat')),
                ('spy_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.spyobject', verbose_name='Spy Object')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
