# Generated by Django 4.2.2 on 2025-06-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_alter_spyobject_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarapplication',
            name='spy_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.spyobject', verbose_name='Spy Object'),
        ),
    ]
