# Generated by Django 4.2.2 on 2025-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_webinarapplication_spy_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spyobject',
            name='source',
            field=models.CharField(choices=[('WEBINAR_SEE_MORE', 'Klik: Webinar przycisk zobacz więcej'), ('VISITED_CLOSED_WEBINAR_PAGE', 'Wejście: Strona szkolenie zamknięte'), ('AGGREGATE_NO_WEBINARS_CLICK_SHOW_FORM', 'Klik: Przycisk Zapisz się Brak Terminów'), ('AGGREGATE_NO_WEBINARS_FORM_SUBMIT', 'Formularz: Brak terminów Przypomnij'), ('WEBINAR_APPLICATION', 'Formularz: Zgłoszenie webinar')], max_length=64, verbose_name='Źródło'),
        ),
    ]
