# Generated by Django 4.2.2 on 2025-06-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0220_alter_spyobject_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingTitleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=32, verbose_name='ID kampanii mailingowej')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł kampanii')),
                ('sha256_hash', models.CharField(blank=True, max_length=80, verbose_name='sha256')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='counter')),
            ],
            options={
                'verbose_name': 'Mailing test tytuł',
                'verbose_name_plural': 'Mailing test tytuł',
            },
        ),
    ]
