# Generated by Django 4.2.2 on 2025-06-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0221_mailingtitletest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='winner_subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Temat (tast a/b winner)'),
        ),
        migrations.AddField(
            model_name='mailingtitletest',
            name='counter_non_bot',
            field=models.PositiveIntegerField(default=0, verbose_name='counter_non_bot'),
        ),
        migrations.AddField(
            model_name='mailingtitletest',
            name='total_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='total_sent'),
        ),
        migrations.AlterField(
            model_name='webinaraggregate',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='UZUPEŁNIA SIĘ AUTOMATYCZNIE', to='core.webinarcategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='webinaraggregate',
            name='closest_webinar_dt',
            field=models.DateTimeField(blank=True, help_text='UZUPEŁNIA SIĘ AUTOMATYCZNIE', null=True),
        ),
        migrations.AlterField(
            model_name='webinaraggregate',
            name='has_active_webinars',
            field=models.BooleanField(default=False, help_text='UZUPEŁNIA SIĘ AUTOMATYCZNIE', verbose_name='Ma aktywne webinary'),
        ),
        migrations.AlterField(
            model_name='webinaraggregate',
            name='webinars',
            field=models.ManyToManyField(blank=True, help_text='UZUPEŁNIA SIĘ AUTOMATYCZNIE', to='core.webinar', verbose_name='Terminy'),
        ),
    ]
