# Generated by Django 4.2.2 on 2025-07-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_mailingcampaign_winner_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceofferapplication',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Nasze uwagi'),
        ),
    ]
