# Generated by Django 4.2.2 on 2025-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0223_serviceofferapplication_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='template_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='template_url'),
        ),
    ]
