# Generated by Django 4.2.2 on 2025-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_mailingcampaign_template_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebinar',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Termin nie będzie widoczny w agragacie', verbose_name='Ukryj termin w Agregacie'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Termin nie będzie widoczny w agragacie', verbose_name='Ukryj termin w Agregacie'),
        ),
    ]
