# Generated by Django 4.2.2 on 2025-07-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0225_alter_historicalwebinar_is_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcampaign',
            name='template_url',
            field=models.CharField(blank=True, max_length=2048, verbose_name='template_url'),
        ),
    ]
