# Generated by Django 4.2.2 on 2025-08-02 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0226_alter_mailingcampaign_template_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_related_webinars', models.BooleanField(default=False, verbose_name='Pokaż szkolenia powiązane tematycznie')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany'), ('archived', 'Zarchiwizowany')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='uploads/blog_covers/%Y/%m/%d/', verbose_name='Zdjęcie okładkowe')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug URL')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Krótki opis')),
                ('content', models.TextField(verbose_name='Treść artykułu')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta tytuł (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta opis (SEO)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Słowa kluczowe (SEO)')),
                ('author', models.CharField(help_text='Autor', max_length=100)),
                ('author_url', models.URLField(blank=True, help_text='Autor URL', null=True)),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Czas czytania (minuty)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Liczba wyświetleń')),
                ('categories', models.ManyToManyField(help_text='Kategorie', related_name='blog_posts', to='core.webinarcategory')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lecturer', verbose_name='Wykładowca')),
            ],
            options={
                'verbose_name': 'Artykuł blogowy',
                'verbose_name_plural': 'Artykuły blogowe',
                'ordering': ['-published_at', '-created_at'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
