# Generated by Django 4.2.2 on 2025-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0227_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='reading_time',
            field=models.CharField(default='5 minut', max_length=20, verbose_name='Czas czytania (minuty)'),
        ),
    ]
