# Generated by Django 4.2.2 on 2025-08-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0228_alter_blogpost_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='program_short',
            field=models.TextField(blank=True, verbose_name='Program szkolenia (krótki)'),
        ),
    ]
