# Generated by Django 4.2.2 on 2025-08-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_webinaraggregate_program_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceofferapplication',
            name='status',
            field=models.CharField(choices=[('SENT', 'Wysłano zgłoszenie'), ('OFFER', 'Oferta wysłana'), ('NO_RESPONSE', 'Brak odpowiedzi'), ('UNCERTAIN', 'Niepewne'), ('ACCEPTED', 'Zaakceptowane'), ('REJECTED', 'Odrzucone'), ('PAID', 'Zrealizowane'), ('DUPLICATE', 'Duplikat zgłoszenia'), ('UNPAID', 'Nie zapłacono za usługę'), ('TRASH', 'Śmieciowe zgłoszenie')], default='SENT', max_length=32),
        ),
    ]
