# Generated by Django 4.2.2 on 2025-08-31 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0230_alter_serviceofferapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceedition',
            name='advert_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinarcategory', verbose_name='Advert Kategoria'),
        ),
        migrations.AddField(
            model_name='conferenceedition',
            name='advert_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lecturer', verbose_name='Advert Wykładowca'),
        ),
    ]
