# Generated by Django 4.2.2 on 2025-09-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0231_conferenceedition_advert_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='advert_aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinaraggregate', verbose_name='Advert Agregat'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='advert_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinarcategory', verbose_name='Advert Kategoria'),
        ),
    ]
