# Generated by Django 4.2.2 on 2025-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0232_blogpost_advert_aggregate_blogpost_advert_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='avatar_transparent',
            field=models.ImageField(blank=True, help_text='Obrazek powinien być dobrej jakościo wymiarach kwadratowych (np. 500px na 500px)', upload_to='uploads/lecturers-transparent', verbose_name='Avatar Transparent'),
        ),
    ]
