# Generated by Django 4.2.2 on 2025-09-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_lecturer_avatar_transparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='title_blogpost_advert',
            field=models.TextField(blank=True, help_text='Max. 220 znaków', max_length=220, verbose_name='Tytuł szkolenia (Blogpost advert)'),
        ),
    ]
