# Generated by Django 4.2.2 on 2025-09-07 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_webinaraggregate_title_blogpost_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertPopup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Zaznacz, aby popup był publicznie widoczny.', verbose_name='Widoczny')),
                ('activate_after', models.DateTimeField(blank=True, help_text='Popup pojawi się na stronie dopiero po tej dacie. Pozostaw puste, aby aktywować natychmiast.', null=True, verbose_name='Aktywuj po dacie')),
                ('disable_after', models.DateTimeField(blank=True, help_text='Popup zniknie ze strony po tej dacie. Pozostaw puste, aby nigdy nie wygasał.', null=True, verbose_name='Dezaktywuj po dacie')),
                ('popup_title', models.CharField(help_text="Główny tekst, który zobaczy użytkownik (np. 'Nowa promocja!').", max_length=100, verbose_name='Tytuł popupa')),
                ('popup_confirm_btn_text', models.CharField(default='Sprawdź', help_text="Tekst na przycisku potwierdzającym (np. 'Dowiedz się więcej').", max_length=50, verbose_name='Tekst przycisku akcji')),
                ('popup_cancel_btn_text', models.CharField(blank=True, default='Zamknij', help_text="Tekst na przycisku zamykającym (np. 'Nie, dziękuję'). Można zostawić puste.", max_length=50, verbose_name='Tekst przycisku anulowania')),
                ('image_url', models.URLField(help_text='Link do grafiki wyświetlanej w popupie.', max_length=512, verbose_name='URL obrazka')),
                ('target_url', models.URLField(help_text='Link, na który zostanie przekierowany użytkownik po kliknięciu przycisku akcji.', max_length=512, verbose_name='Docelowy URL')),
            ],
            options={
                'verbose_name': 'Advert Popup',
                'verbose_name_plural': 'Advert Popups',
                'ordering': ['-created_at'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AdvertPopupClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data kliknięcia')),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertpopup', verbose_name='Advert Popup')),
                ('spy_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.spyobject', verbose_name='Spy Object')),
            ],
            options={
                'verbose_name': 'Advert Popup Click',
                'verbose_name_plural': 'Advert Popup Clicks',
                'ordering': ['-created_at'],
            },
        ),
    ]
