# Generated by Django 4.2.2 on 2025-09-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0235_advertpopup_advertpopupclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertpopup',
            name='show_after_seconds',
            field=models.PositiveIntegerField(default=5, help_text='Liczba sekund po załadowaniu strony, po których popup zostanie pokazany. 0 oznacza natychmiast.', verbose_name='Wyświetl po sekundach'),
        ),
        migrations.AlterField(
            model_name='spyobject',
            name='source',
            field=models.CharField(choices=[('WEBINAR_SEE_MORE', 'Klik: Webinar przycisk zobacz więcej'), ('VISITED_CLOSED_WEBINAR_PAGE', 'Wejście: Strona szkolenie zamknięte'), ('AGGREGATE_NO_WEBINARS_CLICK_SHOW_FORM', 'Klik: Przycisk Zapisz się Brak Terminów'), ('AGGREGATE_NO_WEBINARS_FORM_SUBMIT', 'Formularz: Brak terminów Przypomnij'), ('WEBINAR_APPLICATION', 'Formularz: Zgłoszenie webinar'), ('ADVERT_POPUP_CLICK', 'Advert popup')], max_length=64, verbose_name='Źródło'),
        ),
    ]
