# Generated by Django 4.2.2 on 2025-09-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_advertpopup_show_after_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedwebinarcontactmessage',
            name='spy_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.spyobject', verbose_name='Spy Object'),
        ),
    ]
