# Generated by Django 4.2.2 on 2025-09-15 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0238_alter_spyobject_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('init_status', models.CharField(choices=[('INIT', 'Wstępne przetwarzanie wiadomości'), ('MANUAL_ADMIN', 'Ręczna administracja'), ('AGGRESSOR', 'Agresor zbanowany automatycznie'), ('AUTO_ADMIN', 'Automatyczna administracja (algorytm)'), ('ACCEPTED', 'Wiadomość zaakceptowana'), ('REJECTED', 'Wiadomość odrzucona')], default='INIT', max_length=32, verbose_name='Początkowy status wiadomości')),
            ],
            options={
                'verbose_name': 'Chat konferencji',
                'verbose_name_plural': 'Chaty konferencji',
            },
        ),
        migrations.AddField(
            model_name='conferencefreeparticipant',
            name='banned_from_chat',
            field=models.BooleanField(default=False, verbose_name='Zbanowany z chatu'),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='ip_address',
            field=models.CharField(blank=True, max_length=32, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='show_on_crm_panel',
            field=models.BooleanField(default=True, verbose_name='Pokaż na stronie CRM'),
        ),
        migrations.AlterField(
            model_name='smtpsender',
            name='exclude_from_processing',
            field=models.BooleanField(default=False, verbose_name='Exclude from mailing processing'),
        ),
        migrations.CreateModel(
            name='ConferenceChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('status', models.CharField(choices=[('INIT', 'Wstępne przetwarzanie wiadomości'), ('MANUAL_ADMIN', 'Ręczna administracja'), ('AGGRESSOR', 'Agresor zbanowany automatycznie'), ('AUTO_ADMIN', 'Automatyczna administracja (algorytm)'), ('ACCEPTED', 'Wiadomość zaakceptowana'), ('REJECTED', 'Wiadomość odrzucona')], max_length=32, verbose_name='Status wiadomości')),
                ('message', models.TextField(max_length=500, verbose_name='Treść wiadomości')),
                ('approved', models.BooleanField(default=False, verbose_name='Zaakceptowany')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zaakceptowania wiadomości')),
                ('is_aggressor', models.BooleanField(default=False, verbose_name='Zaakceptowany')),
                ('perspective_score', models.PositiveSmallIntegerField(default=0, verbose_name='Ocena perspektywy')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='core.conferencechat', verbose_name='Chat')),
                ('chat_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_user', to='core.conferencefreeparticipant', verbose_name='Darmowy użytkownik')),
            ],
            options={
                'verbose_name': 'Wiadomość na chacie',
                'verbose_name_plural': 'Wiadomości na chacie',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='conferenceedition',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conferencechat', verbose_name='Chat'),
        ),
    ]
