# Generated by Django 4.2.2 on 2025-09-15 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0239_conferencechat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListRBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Adres listy RBL (np. zen.spamhaus.org).', max_length=255, unique=True)),
                ('list_type', models.CharField(choices=[('ip', 'Adres IP'), ('domain', 'Domena'), ('ip_domain', 'IP i Domena')], default='ip', help_text='Typ elementów, które śledzi ta lista RBL.', max_length=10)),
            ],
            options={
                'verbose_name': 'Lista RBL',
                'verbose_name_plural': 'Listy RBL',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='talos_ip_reputation',
            field=models.CharField(choices=[('POOR', 'Poor'), ('NEUTRAL', 'Neutral'), ('GOOD', 'Good'), ('NO_DATA', 'Brak danych')], default='NO_DATA', max_length=16, verbose_name='talosintelligence reputacja'),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='talos_ip_reputation_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Talos IP Reputation Checked At'),
        ),
        migrations.CreateModel(
            name='MonitorRBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Znacznik czasu, kiedy wykonano sprawdzenie.')),
                ('monitored_item', models.CharField(help_text='Monitorowany adres IP lub domena.', max_length=255)),
                ('response', models.TextField(blank=True, help_text='Odpowiedź otrzymana z serwera RBL.', null=True)),
                ('is_blacklisted', models.BooleanField(default=False, help_text='Wskazuje, czy element został znaleziony na czarnej liście.')),
                ('rbl_list', models.ForeignKey(help_text='Lista RBL, na której dokonano sprawdzenia.', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', to='core.listrbl')),
            ],
            options={
                'verbose_name': 'Wynik monitorowania RBL',
                'verbose_name_plural': 'Wyniki monitorowania RBL',
                'ordering': ['-created_at'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
