# Generated by Django 4.2.2 on 2025-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0240_listrbl_smtpsender_talos_ip_reputation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsender',
            name='monitor_rbl',
            field=models.BooleanField(default=True, verbose_name='Monitoruj listę RBL'),
        ),
    ]
