# Generated by Django 4.2.2 on 2025-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_smtpsender_monitor_rbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorrbl',
            name='monitored_item',
            field=models.CharField(db_index=True, help_text='Monitorowany adres IP lub domena.', max_length=255),
        ),
    ]
