# Generated by Django 4.2.2 on 2025-09-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_alter_monitorrbl_monitored_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listrbl',
            name='is_important_list',
            field=models.BooleanField(default=False, help_text='Ważna lista'),
        ),
    ]
