# Generated by Django 4.2.2 on 2025-09-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_listrbl_is_important_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencechatmessage',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='conferencechatmessage',
            name='approved_at',
        ),
    ]
