# Generated by Django 4.2.2 on 2025-09-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0244_remove_conferencechatmessage_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencechatmessage',
            name='is_aggressor',
        ),
        migrations.AlterField(
            model_name='conferencechatmessage',
            name='perspective_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ocena auto-administrator'),
        ),
    ]
