# Generated by Django 4.2.2 on 2025-09-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_remove_conferencechatmessage_is_aggressor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencechatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat konferencji: Wiadomość na chacie', 'verbose_name_plural': 'Chat konferencji: Wiadomości na chacie'},
        ),
    ]
