# Generated by Django 4.2.2 on 2025-09-19 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0246_alter_conferencechatmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wyświetlenia')),
                ('spy_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.spyobject', verbose_name='Spy Object')),
            ],
            options={
                'verbose_name': 'Blog: Wyświetlenie',
                'verbose_name_plural': 'Blog: Wyświetlenia',
                'ordering': ['-created_at'],
            },
        ),
    ]
