# Generated by Django 4.2.2 on 2025-09-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0248_alter_spyobject_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogview',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.blogpost', verbose_name='Blog post'),
        ),
    ]
