# Generated by Django 4.2.2 on 2025-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_blogview_blog_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog: artykuł', 'verbose_name_plural': 'Blog: artykuły'},
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='base_url_override',
            field=models.CharField(blank=True, help_text='Jeśli base url inny niż https://wykladowca.pl', max_length=128, verbose_name='Nadpisz base url'),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='base_url_override',
            field=models.CharField(blank=True, help_text='Jeśli base url inny niż https://wykladowca.pl', max_length=128, verbose_name='Nadpisz base url'),
        ),
    ]
