# Generated by Django 4.2.2 on 2025-09-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingcampaign',
            name='inherit_bucket_id_from_sender',
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='bucket_id',
            field=models.PositiveSmallIntegerField(default=999),
        ),
    ]
