# Generated by Django 4.2.2 on 2025-09-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0251_remove_mailingcampaign_inherit_bucket_id_from_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceedition',
            name='start_redirecting_participants',
            field=models.BooleanField(default=False, verbose_name='Zacznij przekierowywać uczestników'),
        ),
        migrations.AlterField(
            model_name='conferenceedition',
            name='advert_webinar_html',
            field=models.TextField(blank=True, verbose_name='Advert Webinar HTML'),
        ),
        migrations.AlterField(
            model_name='conferenceedition',
            name='advert_webinar_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Advert Webinar URL'),
        ),
    ]
