# Generated by Django 4.2.2 on 2025-09-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0252_conferenceedition_start_redirecting_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencefreeparticipant',
            name='last_watchroom_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
