# Generated by Django 4.2.2 on 2025-09-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_conferencefreeparticipant_last_watchroom_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingreplymessage',
            name='subject',
            field=models.CharField(max_length=512, verbose_name='Tytuł wiadomości'),
        ),
    ]
