# Generated by Django 4.2.2 on 2025-09-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0254_alter_mailingreplymessage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceedition',
            name='stream_url_embed',
        ),
    ]
