# Generated by Django 4.2.2 on 2025-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_remove_conferenceedition_stream_url_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarcategory',
            name='blog_visible',
            field=models.BooleanField(default=False, verbose_name='Widoczna w blogu'),
        ),
    ]
