# Generated by Django 4.2.2 on 2025-09-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_webinarcategory_blog_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='advert_fixed_html',
            field=models.TextField(blank=True, verbose_name='Reklama fixed'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='advert_sticky_html',
            field=models.TextField(blank=True, verbose_name='Reklama sticky'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_closed_webinar_advert',
            field=models.BooleanField(default=True, verbose_name='Pokaż reklame szkoleń zamkniętych'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug URL'),
        ),
    ]
