# Generated by Django 4.2.2 on 2025-09-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_blogpost_advert_fixed_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarcategory',
            name='advert_blog_fixed_html',
            field=models.TextField(blank=True, verbose_name='Reklama blog fixed'),
        ),
        migrations.AddField(
            model_name='webinarcategory',
            name='advert_blog_sticky_html',
            field=models.TextField(blank=True, verbose_name='Reklama blog sticky'),
        ),
    ]
