# Generated by Django 4.2.2 on 2025-09-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0258_webinarcategory_advert_blog_fixed_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinaraggregate',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.webinarcategory', verbose_name='Kategorie'),
        ),
    ]
