# Generated by Django 4.2.2 on 2025-10-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_alter_webinaraggregate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedwebinarcontactmessage',
            name='number_of_participants',
            field=models.CharField(blank=True, max_length=100, verbose_name='Potencjalna liczba osób do przeszkolenia'),
        ),
    ]
