# Generated by Django 4.2.2 on 2025-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0260_closedwebinarcontactmessage_number_of_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarqueue',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telefon'),
        ),
    ]
