# Generated by Django 4.2.2 on 2025-10-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0261_webinarqueue_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='warmup_max',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='warmup_multiplier',
            field=models.FloatField(default=1.4),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='warmup_status',
            field=models.CharField(choices=[('NO_WARMUP', 'Bez rozgrzewania'), ('WARMUP_ACTIVE', 'Rozgrzewanie aktywne'), ('WARMUP_FINISHED', 'Rozgrzewanie zakończone')], default='NO_WARMUP', max_length=32),
        ),
    ]
