# Generated by Django 4.2.2 on 2025-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_mailingcampaign_warmup_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='allow_sending_to_same_email_a_day',
            field=models.BooleanField(default=False),
        ),
    ]
