# Generated by Django 4.2.2 on 2025-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0263_mailingcampaign_allow_sending_to_same_email_a_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaraggregate',
            name='pod_szkolenie_zamkniete',
            field=models.BooleanField(default=False, help_text='Agregat został stworzony pod szkolenie zamknięte', verbose_name='Pod szkolenie zamknięte'),
        ),
        migrations.AlterField(
            model_name='mailingcampaign',
            name='bucket_id',
            field=models.PositiveSmallIntegerField(default=999, help_text='Wpisz 999, aby bucket został pobrany z konta wysyłkowego'),
        ),
    ]
