# Generated by Django 4.2.2 on 2025-10-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_webinaraggregate_pod_szkolenie_zamkniete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsender',
            name='mailing_server',
            field=models.CharField(blank=True, help_text='Example: N1, N2, S1, S2 ...', max_length=32, verbose_name='Mailing server'),
        ),
    ]
