# Generated by Django 4.2.2 on 2025-10-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0265_smtpsender_mailing_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcampaign',
            name='warmup_max',
            field=models.PositiveIntegerField(default=100000, help_text='Maksymalna ilość wysyłanych maili na godzinę'),
        ),
        migrations.AlterField(
            model_name='mailingcampaign',
            name='warmup_multiplier',
            field=models.FloatField(default=1.4, help_text='Mnożnik warmup'),
        ),
    ]
