# Generated by Django 4.2.2 on 2025-10-15 17:21

import core.models.mailing.smtp_sender_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_alter_mailingcampaign_warmup_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='smtp_sender_override',
            field=models.BooleanField(default=True, help_text='Nadpisuj pola z konta wysyłkowego przy każdym zapisie', verbose_name='SmtpSender Override'),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='allowed_to_send_after',
            field=models.TimeField(default=core.models.mailing.smtp_sender_model.default_allowed_to_send_after, verbose_name='Wysyłaj po godzinie'),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='allowed_to_send_before',
            field=models.TimeField(default=core.models.mailing.smtp_sender_model.default_allowed_to_send_before, verbose_name='Wysyłaj do godziny'),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='sending_batch_size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='sleep_between_batches',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='sleep_every_send',
            field=models.FloatField(default=0.1),
        ),
    ]
