# Generated by Django 4.2.25 on 2025-10-19 09:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0267_mailingcampaign_smtp_sender_override_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='smtpsender',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='smtpsender',
            name='resignation_list',
            field=models.CharField(default='default', max_length=32, verbose_name='Lista rezygnacji'),
        ),
        migrations.AlterField(
            model_name='mailingcampaign',
            name='resignation_list',
            field=models.CharField(default='override', max_length=32, verbose_name='Lista rezygnacji'),
        ),
    ]
