# Generated by Django 4.2.25 on 2025-10-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_alter_smtpsender_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsender',
            name='return_path',
            field=models.CharField(blank=True, max_length=100, verbose_name='Return-Path'),
        ),
    ]
