# Generated by Django 4.2.25 on 2025-10-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0269_smtpsender_return_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcampaign',
            name='filter_bomba',
            field=models.BooleanField(default=True, verbose_name='FILTER_BOMBA'),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='filter_miedzynarodowe',
            field=models.BooleanField(default=True, verbose_name='filter_miedzynarodowe'),
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='filter_ryzykowne',
            field=models.BooleanField(default=True, verbose_name='filter_ryzykowne'),
        ),
    ]
