# Generated by Django 4.2.25 on 2025-10-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_mailingcampaign_filter_bomba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingreplymessage',
            name='email_id',
            field=models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='Message ID'),
        ),
    ]
