# Generated by Django 4.2.25 on 2025-10-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0271_alter_mailingreplymessage_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarrecordingtoken',
            name='participant_extra_info',
            field=models.TextField(blank=True, verbose_name='Dodatkowe informacje o uczestniku'),
        ),
        migrations.AddField(
            model_name='webinarrecordingtoken',
            name='sale_recording_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.salerecordingapplication', verbose_name='Zgłoszenie - nagranie na sprzedaż'),
        ),
        migrations.AddField(
            model_name='webinarrecordingtoken',
            name='sale_recording_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.salerecordingparticipant', verbose_name='Uczestnik - nagranie na sprzedaż'),
        ),
    ]
