# flake8: noqa
from .lecturer_experience_page import lecturer_experience_page
from .lecturer_list_page import lecturer_list_page
from .lecturer_mailing_template_page import lecturer_mailing_template_page
from .lecturer_opinion_form_page import lecturer_opinion_form_page
from .lecturer_opinion_thanks import lecturer_opinion_thanks
from .lecturer_opinions_page import lecturer_opinions_page
from .lecturer_webinars_page import lecturer_webinars_page
