# flake8: noqa
from .mailing_campaign_service import MailingCampaignService
from .mailing_resignation_service import MailingResignationService
from .mailing_webinar_template_service import MailingWebinarTemplateService
